"""Homological-dimension family (Plan 40 / C6): Igusa-Todorov phi/psi, finitistic
bounds, dominant + Gorenstein dimension, Omega/tau-periodicity certificates.

Composed on the existing minimal-resolution / Ext / decompose engines. Every
dimension follows the GlobalDimension honesty rule: a certified value, or a
labeled lower bound / infinite / undecided marker -- never a bare or fabricated
number. The Igusa-Todorov K0 is an ABELIAN-GROUP (Z) computation: integer ranks
via sympy, independent of the algebra's field."""
from __future__ import annotations

from dataclasses import dataclass

from quiverlab.errors import QuiverlabError
from quiverlab.modules.decompose import decompose
from quiverlab.modules.hom import is_isomorphic
from quiverlab.modules.resolution import syzygy


def _is_projective(X, bound=1):
    """True iff ``X`` is projective (pd 0) or the zero module. ``bound=1`` suffices:
    a projective resolves at length 1 (pd 0), anything else has pd >= 1 (pd() is
    then None within depth 1) -- never mistaken for projective."""
    return X.dim == 0 or X.projective_resolution(bound).pd() == 0


# ---------------------------------------------------------------------------
# Igusa-Todorov phi / psi (Igusa-Todorov, Fields Inst. Commun. 45 (2005) 201-204)
# ---------------------------------------------------------------------------
class _K0:
    """Registry of non-projective indecomposable iso-classes discovered on the fly;
    maps a module to its multiplicity vector over the registry (a Z-vector). One
    registry is shared across a whole phi computation so the class indices are stable
    (the same indecomposable always gets the same coordinate)."""

    def __init__(self, budget):
        self.reps = []
        self.budget = budget

    def _index(self, X):
        for i, R in enumerate(self.reps):
            if R.dim == X.dim and is_isomorphic(R, X):    # loud if undecidable
                return i
        self.reps.append(X)
        return len(self.reps) - 1

    def classvec(self, M):
        vec = {}
        for S, mult in decompose(M, budget=self.budget):  # loud on char caveat
            if _is_projective(S):
                continue
            k = self._index(S)
            vec[k] = vec.get(k, 0) + mult
        return vec

    def rank(self, modules):
        """rank of the subgroup of K0 generated by the classes of ``modules`` -- the
        rank of the integer matrix whose rows are their class-vectors (sympy: this is
        an ABELIAN-GROUP rank over Z, not a Domain computation)."""
        import sympy
        vecs = [self.classvec(X) for X in modules if X.dim]
        width = len(self.reps)
        if not vecs or width == 0:
            return 0
        rows = [[v.get(j, 0) for j in range(width)] for v in vecs]
        return sympy.Matrix(rows).rank()


def igusa_todorov_phi(M, budget=512, bound=64):
    """The Igusa-Todorov function ``phi(M)`` (Igusa-Todorov, Fields Inst. Commun. 45
    (2005) 201-204).

    SELF-INJECTIVE SHORT-CIRCUIT (devil's-advocate round, 2026-08-05): over a
    self-injective algebra ``Omega`` is a stable self-equivalence, so ``L`` is
    injective on every ``L^n<M>`` and ``phi(M) = 0`` for EVERY module -- returned
    immediately. Without the guard the rank-registry loop cannot stabilize on any
    self-injective algebra of complexity >= 2 (e.g. the exterior algebra
    Lambda(k^2): syzygy dims 3, 5, 7, ...) and would burn the whole ``bound``
    before refusing. For non-self-injective algebras whose syzygy classes keep
    growing past ``bound`` the loop still refuses loudly -- that refusal is
    honest, not a termination-by-answer guarantee.

    Let ``K0`` be the free abelian group on iso-classes of indecomposable
    NON-projective modules (``[projective] = 0``); ``L: K0 -> K0`` the syzygy operator
    ``L[X] = [Omega X]``; ``<M>`` the subgroup generated by the non-projective
    indecomposable summands of ``M``. The ranks ``r_n = rank(L^n <M>)`` form a
    NON-INCREASING sequence (``L`` maps ``L^n<M>`` ONTO ``L^{n+1}<M>``), hence stabilize.

    ``phi(M)`` is the smallest ``m`` with ``r_n = r_m`` for ALL ``n >= m`` -- i.e. the
    index of the LAST strict decrease. NOTE: this is NOT "the first ``n`` with
    ``r_n = r_{n+1}``": ``L`` injective on ``L^n<M>`` does NOT force injectivity on
    ``L^{n+1}<M>`` (that subgroup need not sit inside ``L^n<M>``), so the sequence can
    read ``1, 1, 0`` -- e.g. ``S_1`` over ``kA_3/rad^2``: ``Omega S_1 = S_2`` (rank 1),
    ``Omega^2 S_1 = P_3`` projective (rank 0), and ``phi(S_1) = pd(S_1) = 2``, not 0.

    Termination is rigorous. (a) When every syzygy has become projective/zero the rank
    is 0 forever (finite projective dimension). (b) Fitting: once the registry of
    distinct non-projective indecomposable classes stops growing, ``L`` is an
    endomorphism of the (now Omega-closed) free group they span, and for an
    endomorphism of a free group of rank ``g`` the sequence ``rank(L^n<M>)`` is constant
    for ``n >= g`` (``L`` is injective on the stabilized image ``im L^g``); so once the
    registry has been unchanged for ``len(reps)+1`` consecutive steps no further drop
    can occur. ``bound`` caps the search and RAISES loudly if neither certificate is
    reached (never a guessed value)."""
    from quiverlab.modules.ext import is_selfinjective
    if M.algebra.quiver is not None and is_selfinjective(M.base_algebra):
        return 0
    K = _K0(budget)
    seq = [S for S, _ in decompose(M, budget=budget) if not _is_projective(S)]
    ranks = [K.rank(seq)]
    reps_at = [len(K.reps)]
    stabilized = not seq
    for n in range(1, bound + 1):
        seq = [Y for X in seq for Y in (syzygy(X),) if Y.dim]
        ranks.append(K.rank(seq))
        reps_at.append(len(K.reps))
        if not seq:                          # (a) finite pd: rank is 0 forever after
            stabilized = True
            break
        w = len(K.reps) + 1                   # (b) Fitting closure window
        if n + 1 >= w and reps_at[-1] == reps_at[-w]:
            stabilized = True
            break
    if not stabilized:
        raise QuiverlabError(
            f"igusa_todorov_phi: rank did not stabilize within depth {bound}",
            hint="raise `bound`; a genuine non-stabilization indicates a K0 bug or a "
                 "module whose syzygies never enter a finite Omega-closed support")
    phi = 0
    for i in range(1, len(ranks)):            # least m with r_n == r_m for all n >= m
        if ranks[i] < ranks[i - 1]:           # == the index of the last strict drop
            phi = i
    return phi


def igusa_todorov_psi(M, budget=512, bound=64):
    """The Igusa-Todorov function ``psi(M) = phi(M) + fpd(Omega^{phi(M)} M)``, where
    ``fpd(N) = max{ pd(Y) : Y a summand of N with pd(Y) < infinity }`` (0 if none)
    (Igusa-Todorov 2005). For finite projective dimension ``psi(M) = phi(M) = pd(M)``.
    Inherits ``decompose``'s loud char-caveat refusal. Self-injective algebras
    short-circuit to 0 (phi = 0 and every finite-pd module is projective, so
    fpd = 0 -- same devil's-advocate guard as phi)."""
    from quiverlab.modules.ext import is_selfinjective
    if M.algebra.quiver is not None and is_selfinjective(M.base_algebra):
        return 0
    phi = igusa_todorov_phi(M, budget=budget, bound=bound)
    W = M
    for _ in range(phi):
        W = syzygy(W)
    fpd = 0
    for Y, _ in decompose(W, budget=budget):
        pdY = Y.projective_resolution(bound).pd()
        if pdY is not None:                   # only finite-pd summands enter fpd
            fpd = max(fpd, pdY)
    return phi + fpd


# ---------------------------------------------------------------------------
# phidim / psidim as ALGEBRA invariants (Plan 53 / R23a). Fernandes-Lanzilotta-
# Mendoza (arXiv:1304.0754) + the survey (arXiv:2310.09283):
#   phidim(A) = sup{ phi(M) : M in mod A },  psidim(A) = sup{ psi(M) };
#   BOTH phi and psi are add-monotone (add M <= add N => phi(M) <= phi(N)); so for a
#   representation-finite A with M0 = (+) all indecomposables, phidim(A) = phi(M0)
#   (a SINGLE evaluation). Self-injective => phidim = psidim = 0 (Plan 40 phi==0).
#   Honest: EXACT only when the AR-knit closes (indecomposable universe finite); else
#   a certified LOWER bound over a finite subfamily (never a claimed sup).
# ---------------------------------------------------------------------------
@dataclass
class PhiDim:
    """The Igusa-Todorov phi-dimension of an algebra, honest (Plan 53). ``value`` is
    the EXACT ``phidim`` when the indecomposable universe closed (``exact=True``) OR a
    certified LOWER bound over a finite subfamily (``exact=False``, add-monotone) --
    never a claimed sup. ``status``: ``"complete"`` (knit closed) / ``"budget"`` (knit
    capped, soft-degraded lower bound) / ``"self-injective"`` (short-circuit to 0)."""
    value: int
    exact: bool
    status: str

    def __int__(self):
        return self.value

    def __eq__(self, other):
        if isinstance(other, PhiDim):
            return ((self.value, self.exact, self.status)
                    == (other.value, other.exact, other.status))
        if isinstance(other, int):
            return self.exact and self.value == other
        return NotImplemented

    __hash__ = None

    def __repr__(self):
        if self.exact:
            return f"phidim = {self.value}"
        return (f">= {self.value} (certified lower bound; the indecomposable universe "
                f"did not close -- knit status {self.status})")


@dataclass
class PsiDim:
    """The Igusa-Todorov psi-dimension of an algebra, honest (Plan 53) -- identical
    shape to :class:`PhiDim` with ``psi`` in place of ``phi``."""
    value: int
    exact: bool
    status: str

    def __int__(self):
        return self.value

    def __eq__(self, other):
        if isinstance(other, PsiDim):
            return ((self.value, self.exact, self.status)
                    == (other.value, other.exact, other.status))
        if isinstance(other, int):
            return self.exact and self.value == other
        return NotImplemented

    __hash__ = None

    def __repr__(self):
        if self.exact:
            return f"psidim = {self.value}"
        return (f">= {self.value} (certified lower bound; the indecomposable universe "
                f"did not close -- knit status {self.status})")


def _dedup_by_iso(modules):
    """De-duplicate ``modules`` up to isomorphism (dim/dim-vector prefilter, then the
    exact ``is_isomorphic`` certificate). A repeated summand does not change phi/psi
    (they read the ADD-closure), so dropping duplicates only saves the ``decompose``
    cost on the ``direct_sum``. Loud when ``is_isomorphic`` is undecidable (unchanged)."""
    reps = []
    for X in modules:
        if X.dim == 0:
            continue
        dvX = X.dimension_vector()
        for R in reps:
            if R.dim == X.dim and R.dimension_vector() == dvX and is_isomorphic(R, X):
                break
        else:
            reps.append(X)
    return reps


def _phipsi_dim(A, fn, cls, *, budget_modules, phi_budget, phi_bound):
    """Shared rep-finite phidim/psidim engine (Plan 53). ``fn`` = ``igusa_todorov_phi``
    or ``igusa_todorov_psi``; ``cls`` = :class:`PhiDim` or :class:`PsiDim`.

    Self-injective short-circuits to the exact ``0`` (Plan 40 phi==0 theorem) BEFORE any
    knit -- ``knit_ar_quiver`` REFUSES self-injective input anyway. Otherwise knit the AR
    quiver and branch on its honest semi-decision (M3, adversarial review -- error and
    budget are NOT the same degrade):
      * ``is_complete``  -> EXACT ``fn(+ all indecomposables)`` (add-monotonicity makes
        the single evaluation the sup);
      * ``status=="budget"`` -> SOFT degrade to the certified LOWER bound over the
        discovered prefix U the simples (a genuine finite subfamily; add-monotone);
      * ``status in {"error","unsupported"}`` -> RAISE loudly (a broken knit is a bug or
        an unhandled input, never a certified partial answer)."""
    from quiverlab.modules.ar import knit_ar_quiver
    from quiverlab.modules.ext import is_selfinjective
    from quiverlab.modules.morphism import direct_sum
    if A.quiver is not None and is_selfinjective(A):
        return cls(0, exact=True, status="self-injective")
    ar = knit_ar_quiver(A, budget_modules=budget_modules)
    if ar.status in ("error", "unsupported"):
        raise QuiverlabError(
            f"phi/psi-dim: the AR knit did not close honestly (status "
            f"{ar.status!r}): {ar.note}",
            hint="a knit error is a bug or an unhandled input -- a lower bound built on "
                 "a broken knit is not certified")
    if ar.is_complete:
        mods = _dedup_by_iso([v["module"] for v in ar.vertices])
        M0, _, _ = direct_sum(*mods)
        return cls(fn(M0, budget=phi_budget, bound=phi_bound),
                   exact=True, status="complete")
    # status == "budget": the discovered prefix U the simples is a finite subfamily; its
    # phi/psi is a rigorous LOWER bound (add-monotonicity), never a claimed sup.
    fam = [v["module"] for v in ar.vertices]
    fam += [A.simple(v) for v in A.quiver.vertices]
    mods = _dedup_by_iso(fam)
    M0, _, _ = direct_sum(*mods)
    return cls(fn(M0, budget=phi_budget, bound=phi_bound),
               exact=False, status="budget")


def phi_dim(A, *, budget_modules=256, phi_budget=512, phi_bound=64):
    """The Igusa-Todorov phi-dimension ``phidim(A) = sup{ phi(M) }`` as an ALGEBRA
    invariant (Plan 53 / R23a; Fernandes-Lanzilotta-Mendoza arXiv:1304.0754).

    EXACT for representation-finite ``A`` via the direct sum of ALL indecomposables
    (add-monotonicity of phi makes the single evaluation the sup -- survey
    arXiv:2310.09283); a certified LOWER bound when the AR knit caps at ``budget_modules``
    (``status="budget"``); the exact ``0`` for self-injective ``A`` (Plan 40 phi==0).
    Inherits ``decompose``'s loud char-caveat refusal (``char <= dim`` over GF(p)); a
    genuine AR-knitting failure raises. Returns a :class:`PhiDim`."""
    return _phipsi_dim(A, igusa_todorov_phi, PhiDim, budget_modules=budget_modules,
                       phi_budget=phi_budget, phi_bound=phi_bound)


def psi_dim(A, *, budget_modules=256, phi_budget=512, phi_bound=64):
    """The Igusa-Todorov psi-dimension ``psidim(A) = sup{ psi(M) }`` as an ALGEBRA
    invariant (Plan 53 / R23a). Same rep-finite ⊕-of-all route + honest degrade as
    :func:`phi_dim`, with ``psi`` in place of ``phi``. Returns a :class:`PsiDim`."""
    return _phipsi_dim(A, igusa_todorov_psi, PsiDim, budget_modules=budget_modules,
                       phi_budget=phi_budget, phi_bound=phi_bound)


def _chain_selfcheck(A, bound=32):
    """The standing chain ``findim(A) <= phidim(A) <= psidim(A) <= gldim(A)`` as a
    self-certificate (Plan 53; survey arXiv:2310.09283). Checks every inequality whose
    BOTH terms are exact/computed: ``findim.lower <= phidim <= psidim``, and (when
    ``gldim`` is exact-finite) ``psidim <= gldim`` PLUS the collapse ``findim = phidim =
    psidim = gldim`` (every module has finite pd, so phi = psi = pd). Returns a dict of
    the computed terms and an ``ok`` flag (True iff every applicable inequality holds)."""
    from quiverlab.modules.ext import global_dimension
    fb = finitistic_dimension_bounds(A, bound=bound)
    pd = phi_dim(A)
    ps = psi_dim(A)
    g = global_dimension(A, bound=bound)
    ok = (fb.lower <= pd.value <= ps.value)
    if g.exact:
        ok = ok and (ps.value <= g.value)
        # gldim exact-finite => all four EQUAL (finite pd everywhere => phi = psi = pd).
        ok = ok and (fb.lower == pd.value == ps.value == g.value)
    return {"ok": bool(ok), "findim_lower": fb.lower, "phidim": pd.value,
            "psidim": ps.value, "gldim": g.value, "gldim_exact": bool(g.exact)}


# ---------------------------------------------------------------------------
# The phi-spectrum + gaps (Plan 53 / R23b; Barrios-Mata-Rama arXiv:1810.12112)
# ---------------------------------------------------------------------------
@dataclass
class PhiSpectrum:
    """The phi-spectrum ``Spec_phi(A) = { phi(X) : X indecomposable }`` (Plan 53). For
    representation-finite ``A`` (``complete=True``) this is a genuine spectrum with
    ``gaps`` = the integers in ``(0, phidim)`` NOT attained by phi (0 and phidim are
    always attained; Barrios-Mata-Rama: 1 and phidim-1 too when ``0 < phidim < oo``).
    A partial spectrum (``complete=False``, knit capped) claims NO gaps -- a "gap" needs
    a proven complete spectrum."""
    values: "list"
    gaps: "list"
    phidim: int
    complete: bool
    status: str


def phi_spectrum(A, *, budget_modules=256):
    """The phi-spectrum of ``A`` (Plan 53 / R23b; Barrios-Mata-Rama arXiv:1810.12112):
    the sorted distinct ``phi`` over the AR-knit indecomposables + its gaps.

    Rep-finite (``knit`` closes): ``values = sorted({ phi(X) })``, ``phidim = max``,
    ``gaps = [g in (0, phidim) if g not in values]`` (0 and phidim are always attained).
    A capped knit degrades to ``complete=False``, ``gaps=[]`` (a partial spectrum claims
    no gaps). Self-injective input has ``phidim = 0`` (Plan 40 phi==0) -- the spectrum is
    ``[0]`` with no knit; a knit ``error``/``unsupported`` raises loudly (the phi_dim
    contract). Inherits ``decompose``'s loud char-caveat refusal."""
    from quiverlab.modules.ar import knit_ar_quiver
    from quiverlab.modules.ext import is_selfinjective
    if A.quiver is not None and is_selfinjective(A):
        return PhiSpectrum([0], [], 0, complete=True, status="self-injective")
    ar = knit_ar_quiver(A, budget_modules=budget_modules)
    if ar.status in ("error", "unsupported"):
        raise QuiverlabError(
            f"phi_spectrum: the AR knit did not close honestly (status "
            f"{ar.status!r}): {ar.note}",
            hint="a knit error is a bug or an unhandled input, not a partial spectrum")
    # The knit vertices are ALREADY one-per-indecomposable, so no dedup is needed.
    values = sorted({igusa_todorov_phi(v["module"]) for v in ar.vertices})
    phidim = max(values) if values else 0
    if ar.is_complete:
        gaps = [g for g in range(1, phidim) if g not in values]
        return PhiSpectrum(values, gaps, phidim, complete=True, status="complete")
    return PhiSpectrum(values, [], phidim, complete=False, status="budget")


# ---------------------------------------------------------------------------
# Dominant dimension (leading projective-injective coresolvents of the regular
# module; self-injective => infinity)
# ---------------------------------------------------------------------------
def _regular_module(A, side="right"):
    """The regular module ``A_A = (+)_v P_v`` (Plan-37 ``direct_sum``)."""
    from quiverlab.modules.morphism import direct_sum
    Ps = [A.projective(v, side=side) for v in A.quiver.vertices]
    D, _, _ = direct_sum(*Ps)
    return D


@dataclass
class DominantDimension:
    """dom.dim A, honest: an exact leading-projective count, a certified lower bound
    (coresolution not resolved within depth), or a certified ``infinite`` (A self-
    injective -- every injective coresolvent of the regular module is projective)."""
    value: "int | None"
    exact: bool
    infinite: bool
    _bound: int = 32

    def __int__(self):
        if self.value is None:
            raise QuiverlabError("dominant dimension is infinite; it has no int value")
        return self.value

    def __eq__(self, other):
        if isinstance(other, DominantDimension):
            return ((self.value, self.exact, self.infinite)
                    == (other.value, other.exact, other.infinite))
        if isinstance(other, int):
            return self.exact and not self.infinite and self.value == other
        return NotImplemented

    def __repr__(self):
        if self.infinite:
            return ("dom.dim = infinity (self-injective; every injective coresolvent "
                    "of A is projective)")
        if self.exact:
            return f"dom.dim = {self.value}"
        return (f">= {self.value} (certified lower bound; not resolved within depth "
                f"{self._bound})")


def dominant_dimension(A, bound=32):
    """dom.dim A = the index of the first term in a minimal injective coresolution of
    the regular right module ``A_A = (+)_v P_v`` that is NOT projective. Self-injective
    algebras have every term projective, hence infinite dominant dimension (that
    direction is a theorem and is the only ``infinite`` this function claims; the
    CONVERSE -- dom.dim = infinity implies self-injective -- is the open Nakayama
    conjecture and is deliberately NOT assumed) (Assem-Simson-Skowronski)."""
    from quiverlab.modules.ext import is_selfinjective
    from quiverlab.modules.injective import injective_resolution
    if is_selfinjective(A):
        return DominantDimension(None, exact=False, infinite=True, _bound=bound)
    reg = _regular_module(A)
    res = injective_resolution(reg, bound)
    count = 0
    for n in range(bound + 1):
        term = res.terms[n] if n < len(res.terms) else None
        if term is None or term.dim == 0:                 # coresolution ended proj.
            return DominantDimension(count, exact=True, infinite=False, _bound=bound)
        if term.projective_resolution(1).pd() == 0:        # E^n projective: it counts
            count += 1
        else:
            return DominantDimension(count, exact=True, infinite=False, _bound=bound)
    return DominantDimension(count, exact=False, infinite=False, _bound=bound)  # bound


# ---------------------------------------------------------------------------
# Gorenstein dimension + is_gorenstein (both-sided injective dimension of the
# regular module; three-valued True/None -- never a bare False)
# ---------------------------------------------------------------------------
def _regular_injective_dimension(A, bound):
    from quiverlab.modules.injective import injective_dimension
    return injective_dimension(_regular_module(A), bound=bound)


@dataclass
class GorensteinDimension:
    """The (Iwanaga-)Gorenstein data of A: the injective dimension of the regular
    module on the right (``A_A``) and left (``_A A``) sides. ``is_gorenstein`` is
    three-valued True/None: True iff BOTH sides resolve finite; None when either is a
    mere lower bound -- the bounded engine never proves an infinite injective
    dimension, so a bare ``False`` is never emitted (Plan 40 honesty rule)."""
    right_id: "int | None"
    left_id: "int | None"
    is_gorenstein: "bool | None"
    _bound: int = 32

    def __repr__(self):
        if self.right_id is not None and self.left_id is not None:
            return (f"Gorenstein: right inj.dim {self.right_id}, "
                    f"left inj.dim {self.left_id}")
        return (f"undecided within depth {self._bound} (an injective dimension did not "
                "resolve; infinity is not proven)")


def gorenstein_dimension(A, bound=32):
    """A is (Iwanaga-)Gorenstein iff the right AND left injective dimensions of the
    regular module are both finite. ``is_gorenstein`` is True when both resolve within
    ``bound``, else None (never a bare False -- see the honesty note) (spec section
    3.5; Assem-Simson-Skowronski)."""
    right = _regular_injective_dimension(A, bound)
    left = _regular_injective_dimension(A.opposite(), bound)
    both_finite = right is not None and left is not None
    verdict = True if both_finite else None            # never a bare False
    return GorensteinDimension(right, left, verdict, _bound=bound)


def is_gorenstein(A, bound=32):
    """Three-valued Gorenstein verdict: True (both injective dimensions finite) or None
    (an injective dimension did not resolve within ``bound``; infinity is not proven --
    never False) (Plan 40)."""
    return gorenstein_dimension(A, bound).is_gorenstein


# ---------------------------------------------------------------------------
# Omega- and tau-periodicity certificates (is_isomorphic-certified)
# ---------------------------------------------------------------------------
def omega_periodicity(M, max_period=12, bound=64):
    """The least ``k`` in ``1..max_period`` with ``Omega^k M ~ M`` (is_isomorphic-
    certified), else ``None`` -- including when some ``Omega^i M = 0`` (finite
    projective dimension => not Omega-periodic). Raises the ``is_isomorphic`` loud
    refusal unchanged when an iso comparison is undecidable (Plan 40)."""
    if M.dim == 0 or _is_projective(M):
        return None
    cur = M
    for k in range(1, max_period + 1):
        cur = syzygy(cur)
        if cur.dim == 0:                     # finite projective dimension
            return None
        if cur.dim == M.dim and is_isomorphic(cur, M):   # loud if undecidable
            return k
    return None


def tau_periodicity(M, max_period=12):
    """The least ``k`` in ``1..max_period`` with ``tau^k M ~ M`` (is_isomorphic-
    certified), else ``None`` (a ``tau^i M = 0`` => the tau-orbit terminates => not
    periodic). Raises the ``is_isomorphic`` loud refusal unchanged when undecidable
    (Plan 40)."""
    if M.dim == 0 or _is_projective(M):
        return None
    cur = M
    for k in range(1, max_period + 1):
        cur = cur.tau()
        if cur.dim == 0:                     # tau-orbit terminated (hit a projective)
            return None
        if cur.dim == M.dim and is_isomorphic(cur, M):
            return k
    return None


# ---------------------------------------------------------------------------
# Lat-Igusa-Todorov finitistic certificate (Plan 53 / R23c; Bravo-Lanzilotta-
# Mendoza-Vivero arXiv:2002.07866). FOUR decidable families each emit a proof-
# carrying certified finite findim upper bound; "no known decision procedure in
# general" (NOT undecidable) elsewhere. This is what flips Plan 40's honest None.
# ---------------------------------------------------------------------------
@dataclass
class LITCertificate:
    """A Lat-Igusa-Todorov finitistic certificate (Plan 53). ``findim_upper`` is a
    CERTIFIED finite ``findim`` upper bound from a decidable LIT family, or an honest
    ``None`` (no known decision procedure in general). ``family`` names the decidable
    family; ``proof`` is the proof-carrying justification (the theorem + the numbers)."""
    findim_upper: "int | None"
    family: "str | None"
    proof: str

    def __repr__(self):
        if self.family is not None:
            return f"findim(A) <= {self.findim_upper}  [{self.family}: {self.proof}]"
        return ("no known decision procedure for a finite findim bound here "
                "(A is not in a shipped LIT-decidable family)")


def _lit_family4_bound(psi_D_of_V, n, known_findim=None):
    """The LIT family-4 (finite one-sided ``id(A_A)``) proof-carrying bound
    ``findim(A) <= psi_D(V) + n + 1`` (Bravo-Lanzilotta-Mendoza-Vivero 2002.07866;
    R23c). DEMOTED machinery: family 4 fires only when families 1-3 fail yet
    ``id(A_A) < infinity`` -- i.e. ``id(A_A)`` finite while ``id(_AA)`` infinite -- and
    the bounded engine NEVER proves an injective dimension infinite, so this precondition
    is not decidably reachable with shipped tools. Hence this combinator is NOT wired into
    :func:`lit_finitistic_certificate` (which returns ``None`` there); it ships + is
    unit-covered on constructed ``(D, n)`` data.

    ``psi_D_of_V`` = the generalised Igusa-Todorov function ``psi_D`` evaluated on the
    generators ``V`` of the subcategory ``D`` (# PIN: the exact ``psi_D``/``V`` are pinned
    from 2002.07866 -- transcribed as inputs here, not recomputed, pending the
    Asashiba-type transcription successor); ``n`` = the LIT datum. The ``+ n + 1``
    constant is the record's; ARBITRATION safety gate (the Plan 40 rule -- never a bound
    below a KNOWN exact findim): if ``known_findim`` is given and the bound would
    undershoot it, RAISE loudly (a mis-transcribed constant is a bug, never clamped)."""
    bound = int(psi_D_of_V) + int(n) + 1
    if known_findim is not None and bound < known_findim:
        raise QuiverlabError(
            f"LIT family-4 bound {bound} < a known exact findim {known_findim}: the "
            f"psi_D(V) + n + 1 constant is mis-transcribed for this datum",
            hint="the record's + n + 1 must never undershoot the family-1/2 exact "
                 "values; re-check the 2002.07866 statement, do not clamp")
    return bound


def lit_finitistic_certificate(A, bound=32):
    """A Lat-Igusa-Todorov finitistic certificate for ``A`` (Plan 53 / R23c;
    Bravo-Lanzilotta-Mendoza-Vivero arXiv:2002.07866): tries the FOUR decidable families
    1->2->3->4 and returns the FIRST that applies (the sharpest is usually earliest).

    1. **Self-injective** (``is_selfinjective``) -- ``D = mod A``, ``n = 0``; only
       projectives have finite pd, so ``findim(A) = 0``.
    2. **Iwanaga-Gorenstein** (``gorenstein_dimension`` both-sided finite) -- ``D =
       Gproj(A)``; ``findim(A) = id(A_A) = id(_AA)`` = the Gorenstein dimension
       ``max(right_id, left_id)`` (for finite gl.dim this equals ``gl.dim``).
    3. **Finite phidim** (rep-finite, :func:`phi_dim` exact) -- the chain gives
       ``findim(A) <= phidim(A)``, a certified finite bound.
    4. **Finite one-sided id(A_A)** -- DEMOTED: not decidably reachable (the bounded
       engine never proves an injective dimension infinite, so the "one-sided-finite,
       not Gorenstein" precondition is not certifiable); the ``psi_D(V) + n + 1``
       machinery ships as :func:`_lit_family4_bound` but is NOT wired here.

    Returns a :class:`LITCertificate` with a finite ``findim_upper`` + ``family`` label +
    ``proof``, or ``findim_upper=None``/``family=None`` ("no known decision procedure in
    general" -- NOT undecidable). The family-3 :func:`phi_dim` probe degrades quietly if
    it cannot be certified (char caveat / knit error) -- an uncertifiable phidim is not a
    family-3 certificate."""
    from quiverlab.modules.ext import is_selfinjective
    # Family 1: self-injective => findim = 0.
    if A.quiver is not None and is_selfinjective(A):
        return LITCertificate(
            0, "self-injective",
            proof="self-injective (D = mod A, n = 0): only projectives have finite "
                  "projective dimension, so findim(A) = 0 (2002.07866)")
    # Family 2: Iwanaga-Gorenstein => findim = id(A_A) = id(_AA) = Gorenstein dimension.
    gd = gorenstein_dimension(A, bound=bound)
    if gd.is_gorenstein:                    # both-sided injective dimension finite
        fd = max(gd.right_id, gd.left_id)
        return LITCertificate(
            fd, "gorenstein",
            proof=f"Iwanaga-Gorenstein (D = Gproj A): findim(A) = id(A_A) = id(_AA) = "
                  f"{fd}, the Gorenstein dimension (2002.07866)")
    # Family 3: finite phidim (rep-finite) => findim <= phidim (the standing chain).
    try:
        pd = phi_dim(A)
    except QuiverlabError:
        pd = None                            # uncertifiable phidim is not a certificate
    if pd is not None and pd.exact:
        return LITCertificate(
            pd.value, "finite-phidim",
            proof=f"finite phi-dimension: findim(A) <= phidim(A) = {pd.value} (the "
                  f"chain findim <= phidim; Fernandes-Lanzilotta-Mendoza 1304.0754)")
    # Family 4: not decidably reachable (see _lit_family4_bound). Honest degrade.
    return LITCertificate(
        None, None,
        proof="no known decision procedure for a finite findim bound here (A is not "
              "in a shipped LIT-decidable family)")


# ---------------------------------------------------------------------------
# Finitistic-dimension bounds (rigorous lower; gl.dim upper when finite, honest
# degrade otherwise)
# ---------------------------------------------------------------------------
@dataclass
class FinitisticBounds:
    """findim A = sup{ pd N : pd N < infinity }, bracketed honestly. ``lower`` is a
    genuine lower bound (a finite pd actually found); ``upper`` is gl.dim when finite
    (findim = gl.dim then) or ``None`` (honest degrade -- no folklore number). ``exact``
    iff ``lower == upper`` both finite."""
    lower: int
    upper: "int | None"
    exact: bool
    note: str

    def __repr__(self):
        if self.exact:
            return f"findim = {self.lower}"
        if self.upper is not None:
            return f"findim in [{self.lower}, {self.upper}]"
        return f">= {self.lower} (upper bound undetermined)"


def _finite_pd_probe_lower(A, bound):
    """Max finite pd over ``{ S_v } U { Omega S_v } U { radical layers of P_v }`` -- a
    rigorous lower bound: any finite pd found is a valid ``findim`` witness. The simples
    are included, so this reaches ``gl.dim`` exactly whenever ``gl.dim`` is finite."""
    lower = 0
    probes = []
    for v in A.quiver.vertices:
        Sv = A.simple(v)
        probes.append(Sv)
        probes.append(syzygy(Sv))
        layer = A.projective(v)                # walk rad^k P_v until zero
        while layer.dim:
            probes.append(layer)
            layer = layer.radical()
    for N in probes:
        if N.dim == 0:
            continue
        pd = N.projective_resolution(bound).pd()
        if pd is not None:                     # only FINITE pd enters the lower bound
            lower = max(lower, pd)
    return lower


def _igusa_todorov_finitistic_upper(A, bound):
    """The Igusa-Todorov psi-finitistic UPPER bound -- HONEST-DEGRADED to ``None``.

    THEOREM PINNED (Igusa-Todorov, "On the finitistic global dimension conjecture for
    Artin algebras", Fields Inst. Commun. 45 (2005), 201-204). For a short exact
    sequence ``0 -> A -> B -> C -> 0`` of f.d. modules with ``pd C < infinity``,
    ``pd C <= psi(A (+) B) + 1``. Applied to the syzygy sequence
    ``0 -> Omega M -> P -> M -> 0`` (``P`` a projective cover) of any FINITE-pd ``M``,
    and using ``psi(X (+) projective) = psi(X)``, this gives the genuine PER-MODULE
    bound ``pd M <= psi(Omega M) + 1`` (constant ``+1``, from the one-term syzygy
    sequence -- this is where the additive constant is fixed by the theorem itself).

    WHY THE AGGREGATE ``psi((+)_v Omega S_v) + 1`` IS *NOT* SHIPPED AS ``findim``'s upper
    bound. Bounding ``findim = sup{ pd M : pd M < infinity }`` needs ``sup_M psi(Omega
    M)``, and ``psi(Omega M)`` for an arbitrary finite-pd ``M`` is NOT controlled by
    ``psi((+)_v Omega S_v)``: ``Omega M`` need not lie in ``add((+)_v Omega S_v)`` (a
    general syzygy is not built from the syzygies of the simples). More decisively, a
    finite GENERAL upper bound for ``findim`` computed from the presentation would
    resolve the finitistic dimension conjecture (findim ``< infinity`` for every Artin
    algebra), which is OPEN. So no such certified finite bound exists for a general
    algebra with infinite global dimension; a specific ``psi(...) + const`` number here
    would be folklore, exactly what the house honesty rule forbids -- so the constant is
    NOT "arbitrated" into a shipped number, the whole aggregate is degraded.

    Hence this returns ``None`` (honest degrade). The only certified finite upper bound
    this surface ships is ``gl.dim`` when it is finite (``findim = gl.dim`` then), in
    :func:`finitistic_dimension_bounds`. A successor plan that supplies a certified
    finite-representation-dimension witness ``V`` (so ``add V`` contains every relevant
    syzygy) can then ship ``psi(V) + 1`` as a genuine bound and flip this degrade."""
    return None


def finitistic_dimension_bounds(A, bound=32):
    """``findim A`` bracketed honestly (Plan 40). Lower bound: the max finite pd over
    ``{S_v} U {Omega S_v} U {rad-layers of P_v}`` (rigorous). Upper bound: ``gl.dim``
    when exact-finite (``findim = gl.dim``, ``exact=True``); otherwise ``None`` (the
    Igusa-Todorov psi-bound is not a certifiable general theorem -- see
    :func:`_igusa_todorov_finitistic_upper`). A numeric ``upper`` is ALWAYS ``>= lower``
    (a violation is a mis-implementation -- raised, never clamped)."""
    from quiverlab.modules.ext import global_dimension
    lower = _finite_pd_probe_lower(A, bound)
    g = global_dimension(A, bound=bound)
    if g.exact:
        upper = g.value
        # findim <= gl.dim, equality when gl.dim finite; the simple probes make lower
        # >= max_v pd(S_v) = gl.dim, so lower == upper == gl.dim here.
        assert upper >= lower, "finitistic lower bound exceeded gl.dim (bug)"
        return FinitisticBounds(lower, upper, exact=True,
                                note="gl.dim exact and finite => findim = gl.dim")
    # gl.dim not exact-finite: consult the LIT certificate BEFORE the honest degrade
    # (Plan 53 / R23c). A decidable LIT family (self-injective / Iwanaga-Gorenstein /
    # finite-phidim) supplies a CERTIFIED finite upper exactly where Plan 40 degraded to
    # None; `exact` stays False (the exact=True flag is reserved for the gl.dim=findim
    # collapse -- Plan 40's test pins it), and the mandatory upper >= lower gate holds.
    cert = lit_finitistic_certificate(A, bound=bound)
    if cert.findim_upper is not None:
        if cert.findim_upper < lower:
            raise QuiverlabError(
                "finitistic upper bound < lower bound: the LIT certificate is "
                "mis-implemented for this presentation")
        return FinitisticBounds(lower, cert.findim_upper, exact=False,
                                note=f"LIT [{cert.family}]: {cert.proof}")
    upper = _igusa_todorov_finitistic_upper(A, bound)   # int or None (None here)
    if upper is not None and upper < lower:
        raise QuiverlabError(                           # the mandated sanity gate
            "finitistic upper bound < lower bound: the Igusa-Todorov bound is "
            "mis-implemented for this presentation")
    return FinitisticBounds(
        lower, upper, exact=False,
        note=("Igusa-Todorov psi-bound" if upper is not None
              else "upper bound undetermined (Igusa-Todorov psi-bound not certified "
                   "for this presentation)"))


# ---------------------------------------------------------------------------
# The homological_profile no-code block (Plan 40 Task H) -- ONE shared library
# builder, so the server (hpc.spec) and Pyodide (docs/gui/runner) twins are
# byte-identical by construction. Each runner adds the resolved `citations`.
# ---------------------------------------------------------------------------
def _igusa_todorov_entry(A, bound):
    """The phi/psi of ``(+)_v S_v`` for the profile block, or a per-entry error dict
    when the K0 bookkeeping refuses (the decompose char<=dim caveat) -- honest per
    entry, never a silent omission (Plan-30 tau-block precedent)."""
    from quiverlab.modules.morphism import direct_sum
    try:
        simples = [A.simple(v) for v in A.quiver.vertices]
        M, _, _ = direct_sum(*simples)
        return {"module": "(+)_v S_v",
                "phi": igusa_todorov_phi(M, bound=bound),
                "psi": igusa_todorov_psi(M, bound=bound)}
    except QuiverlabError as exc:
        return {"error": str(exc)}


def _phidim_profile_entry(A, fn, cls_name):
    """phidim/psidim for the profile block, honest-noted; the decompose char-caveat
    refusal (or a knit error) is caught into ``{"error": ...}`` (the Plan-40 IT-entry
    precedent), never a silent omission."""
    try:
        d = _phipsi_dim(A, (igusa_todorov_phi if fn == "phi" else igusa_todorov_psi),
                        (PhiDim if fn == "phi" else PsiDim),
                        budget_modules=256, phi_budget=512, phi_bound=64)
        return {"value": d.value, "exact": bool(d.exact), "status": d.status,
                "text": str(d)}
    except QuiverlabError as exc:
        return {"error": str(exc)}


def _phi_spectrum_profile_entry(A):
    """The phi-spectrum for the profile block, honest-noted; the decompose char-caveat
    (or a knit error) is caught into ``{"error": ...}``."""
    try:
        S = phi_spectrum(A)
        return {"values": list(S.values), "gaps": list(S.gaps),
                "complete": bool(S.complete), "status": S.status}
    except QuiverlabError as exc:
        return {"error": str(exc)}


def homological_profile(A, bound=32):
    """The whole C6 homological-dimension family as ONE block (Plan 40 + Plan 53):
    global / finitistic / dominant / Gorenstein dimensions + the Igusa-Todorov phi/psi
    of ``(+)_v S_v`` + (Plan 53, ADDITIVE keys) the phidim/psidim ALGEBRA invariants, the
    phi-spectrum + gaps, and the Lat-Igusa-Todorov finitistic certificate. Every entry
    carries its own honesty (exact/lower-bound/infinite/undecided markers or a per-entry
    error). The Plan-53 keys are strictly ADDITIVE -- the block name is unchanged, so
    canonical cache keys are unaffected and pre-P53 cached blocks (missing the four new
    keys) replay under renderer tolerance. Returns the block minus ``citations`` (each
    runner resolves ``references`` to citation pairs)."""
    from quiverlab.modules.ext import global_dimension
    g = global_dimension(A, bound=bound)
    fb = finitistic_dimension_bounds(A, bound=bound)
    dd = dominant_dimension(A, bound=bound)
    gd = gorenstein_dimension(A, bound=bound)
    lit = lit_finitistic_certificate(A, bound=bound)
    return {
        "kind": "homological_profile",
        "global_dimension": {"text": str(g), "exact": bool(g.exact), "value": g.value},
        "finitistic": {"lower": fb.lower, "upper": fb.upper,
                       "exact": bool(fb.exact), "note": fb.note},
        "dominant": {"value": dd.value, "exact": bool(dd.exact),
                     "infinite": bool(dd.infinite), "text": str(dd)},
        "gorenstein": {"right_id": gd.right_id, "left_id": gd.left_id,
                       "is_gorenstein": gd.is_gorenstein, "text": str(gd)},
        "igusa_todorov": _igusa_todorov_entry(A, bound),
        # Plan 53 (R23a/b/c) -- additive keys:
        "phidim": _phidim_profile_entry(A, "phi", "PhiDim"),
        "psidim": _phidim_profile_entry(A, "psi", "PsiDim"),
        "phi_spectrum": _phi_spectrum_profile_entry(A),
        "lit": {"findim_upper": lit.findim_upper, "family": lit.family,
                "proof": lit.proof},
        "references": ["igusa_todorov", "assem_book", "fernandes_lanzilotta_mendoza",
                       "barrios_mata", "bravo_lanzilotta_mendoza_vivero"],
    }
