"""Homological-dimension family (Plan 40 / C6): Igusa-Todorov phi/psi, finitistic
bounds, dominant + Gorenstein dimension, Omega/tau-periodicity certificates.

Composed on the existing minimal-resolution / Ext / decompose engines. Every
dimension follows the GlobalDimension honesty rule: a certified value, or a
labeled lower bound / infinite / undecided marker -- never a bare or fabricated
number. The Igusa-Todorov K0 is an ABELIAN-GROUP (Z) computation: integer ranks
via sympy, independent of the algebra's field."""
from __future__ import annotations

from dataclasses import dataclass

from quiverlab.errors import QuiverlabError
from quiverlab.modules.decompose import decompose
from quiverlab.modules.hom import is_isomorphic
from quiverlab.modules.resolution import syzygy


def _is_projective(X, bound=1):
    """True iff ``X`` is projective (pd 0) or the zero module. ``bound=1`` suffices:
    a projective resolves at length 1 (pd 0), anything else has pd >= 1 (pd() is
    then None within depth 1) -- never mistaken for projective."""
    return X.dim == 0 or X.projective_resolution(bound).pd() == 0


# ---------------------------------------------------------------------------
# Igusa-Todorov phi / psi (Igusa-Todorov, Fields Inst. Commun. 45 (2005) 201-204)
# ---------------------------------------------------------------------------
class _K0:
    """Registry of non-projective indecomposable iso-classes discovered on the fly;
    maps a module to its multiplicity vector over the registry (a Z-vector). One
    registry is shared across a whole phi computation so the class indices are stable
    (the same indecomposable always gets the same coordinate)."""

    def __init__(self, budget):
        self.reps = []
        self.budget = budget

    def _index(self, X):
        for i, R in enumerate(self.reps):
            if R.dim == X.dim and is_isomorphic(R, X):    # loud if undecidable
                return i
        self.reps.append(X)
        return len(self.reps) - 1

    def classvec(self, M):
        vec = {}
        for S, mult in decompose(M, budget=self.budget):  # loud on char caveat
            if _is_projective(S):
                continue
            k = self._index(S)
            vec[k] = vec.get(k, 0) + mult
        return vec

    def rank(self, modules):
        """rank of the subgroup of K0 generated by the classes of ``modules`` -- the
        rank of the integer matrix whose rows are their class-vectors (sympy: this is
        an ABELIAN-GROUP rank over Z, not a Domain computation)."""
        import sympy
        vecs = [self.classvec(X) for X in modules if X.dim]
        width = len(self.reps)
        if not vecs or width == 0:
            return 0
        rows = [[v.get(j, 0) for j in range(width)] for v in vecs]
        return sympy.Matrix(rows).rank()


def igusa_todorov_phi(M, budget=512, bound=64):
    """The Igusa-Todorov function ``phi(M)`` (Igusa-Todorov, Fields Inst. Commun. 45
    (2005) 201-204).

    Let ``K0`` be the free abelian group on iso-classes of indecomposable
    NON-projective modules (``[projective] = 0``); ``L: K0 -> K0`` the syzygy operator
    ``L[X] = [Omega X]``; ``<M>`` the subgroup generated by the non-projective
    indecomposable summands of ``M``. The ranks ``r_n = rank(L^n <M>)`` form a
    NON-INCREASING sequence (``L`` maps ``L^n<M>`` ONTO ``L^{n+1}<M>``), hence stabilize.

    ``phi(M)`` is the smallest ``m`` with ``r_n = r_m`` for ALL ``n >= m`` -- i.e. the
    index of the LAST strict decrease. NOTE: this is NOT "the first ``n`` with
    ``r_n = r_{n+1}``": ``L`` injective on ``L^n<M>`` does NOT force injectivity on
    ``L^{n+1}<M>`` (that subgroup need not sit inside ``L^n<M>``), so the sequence can
    read ``1, 1, 0`` -- e.g. ``S_1`` over ``kA_3/rad^2``: ``Omega S_1 = S_2`` (rank 1),
    ``Omega^2 S_1 = P_3`` projective (rank 0), and ``phi(S_1) = pd(S_1) = 2``, not 0.

    Termination is rigorous. (a) When every syzygy has become projective/zero the rank
    is 0 forever (finite projective dimension). (b) Fitting: once the registry of
    distinct non-projective indecomposable classes stops growing, ``L`` is an
    endomorphism of the (now Omega-closed) free group they span, and for an
    endomorphism of a free group of rank ``g`` the sequence ``rank(L^n<M>)`` is constant
    for ``n >= g`` (``L`` is injective on the stabilized image ``im L^g``); so once the
    registry has been unchanged for ``len(reps)+1`` consecutive steps no further drop
    can occur. ``bound`` caps the search and RAISES loudly if neither certificate is
    reached (never a guessed value)."""
    K = _K0(budget)
    seq = [S for S, _ in decompose(M, budget=budget) if not _is_projective(S)]
    ranks = [K.rank(seq)]
    reps_at = [len(K.reps)]
    stabilized = not seq
    for n in range(1, bound + 1):
        seq = [Y for X in seq for Y in (syzygy(X),) if Y.dim]
        ranks.append(K.rank(seq))
        reps_at.append(len(K.reps))
        if not seq:                          # (a) finite pd: rank is 0 forever after
            stabilized = True
            break
        w = len(K.reps) + 1                   # (b) Fitting closure window
        if n + 1 >= w and reps_at[-1] == reps_at[-w]:
            stabilized = True
            break
    if not stabilized:
        raise QuiverlabError(
            f"igusa_todorov_phi: rank did not stabilize within depth {bound}",
            hint="raise `bound`; a genuine non-stabilization indicates a K0 bug or a "
                 "module whose syzygies never enter a finite Omega-closed support")
    phi = 0
    for i in range(1, len(ranks)):            # least m with r_n == r_m for all n >= m
        if ranks[i] < ranks[i - 1]:           # == the index of the last strict drop
            phi = i
    return phi


def igusa_todorov_psi(M, budget=512, bound=64):
    """The Igusa-Todorov function ``psi(M) = phi(M) + fpd(Omega^{phi(M)} M)``, where
    ``fpd(N) = max{ pd(Y) : Y a summand of N with pd(Y) < infinity }`` (0 if none)
    (Igusa-Todorov 2005). For finite projective dimension ``psi(M) = phi(M) = pd(M)``.
    Inherits ``decompose``'s loud char-caveat refusal."""
    phi = igusa_todorov_phi(M, budget=budget, bound=bound)
    W = M
    for _ in range(phi):
        W = syzygy(W)
    fpd = 0
    for Y, _ in decompose(W, budget=budget):
        pdY = Y.projective_resolution(bound).pd()
        if pdY is not None:                   # only finite-pd summands enter fpd
            fpd = max(fpd, pdY)
    return phi + fpd
