"""Homological-dimension family (Plan 40 / C6): Igusa-Todorov phi/psi, finitistic
bounds, dominant + Gorenstein dimension, Omega/tau-periodicity certificates.

Composed on the existing minimal-resolution / Ext / decompose engines. Every
dimension follows the GlobalDimension honesty rule: a certified value, or a
labeled lower bound / infinite / undecided marker -- never a bare or fabricated
number. The Igusa-Todorov K0 is an ABELIAN-GROUP (Z) computation: integer ranks
via sympy, independent of the algebra's field."""
from __future__ import annotations

from dataclasses import dataclass

from quiverlab.errors import QuiverlabError
from quiverlab.modules.decompose import decompose
from quiverlab.modules.hom import is_isomorphic
from quiverlab.modules.resolution import syzygy


def _is_projective(X, bound=1):
    """True iff ``X`` is projective (pd 0) or the zero module. ``bound=1`` suffices:
    a projective resolves at length 1 (pd 0), anything else has pd >= 1 (pd() is
    then None within depth 1) -- never mistaken for projective."""
    return X.dim == 0 or X.projective_resolution(bound).pd() == 0


# ---------------------------------------------------------------------------
# Igusa-Todorov phi / psi (Igusa-Todorov, Fields Inst. Commun. 45 (2005) 201-204)
# ---------------------------------------------------------------------------
class _K0:
    """Registry of non-projective indecomposable iso-classes discovered on the fly;
    maps a module to its multiplicity vector over the registry (a Z-vector). One
    registry is shared across a whole phi computation so the class indices are stable
    (the same indecomposable always gets the same coordinate)."""

    def __init__(self, budget):
        self.reps = []
        self.budget = budget

    def _index(self, X):
        for i, R in enumerate(self.reps):
            if R.dim == X.dim and is_isomorphic(R, X):    # loud if undecidable
                return i
        self.reps.append(X)
        return len(self.reps) - 1

    def classvec(self, M):
        vec = {}
        for S, mult in decompose(M, budget=self.budget):  # loud on char caveat
            if _is_projective(S):
                continue
            k = self._index(S)
            vec[k] = vec.get(k, 0) + mult
        return vec

    def rank(self, modules):
        """rank of the subgroup of K0 generated by the classes of ``modules`` -- the
        rank of the integer matrix whose rows are their class-vectors (sympy: this is
        an ABELIAN-GROUP rank over Z, not a Domain computation)."""
        import sympy
        vecs = [self.classvec(X) for X in modules if X.dim]
        width = len(self.reps)
        if not vecs or width == 0:
            return 0
        rows = [[v.get(j, 0) for j in range(width)] for v in vecs]
        return sympy.Matrix(rows).rank()


def igusa_todorov_phi(M, budget=512, bound=64):
    """The Igusa-Todorov function ``phi(M)`` (Igusa-Todorov, Fields Inst. Commun. 45
    (2005) 201-204).

    Let ``K0`` be the free abelian group on iso-classes of indecomposable
    NON-projective modules (``[projective] = 0``); ``L: K0 -> K0`` the syzygy operator
    ``L[X] = [Omega X]``; ``<M>`` the subgroup generated by the non-projective
    indecomposable summands of ``M``. The ranks ``r_n = rank(L^n <M>)`` form a
    NON-INCREASING sequence (``L`` maps ``L^n<M>`` ONTO ``L^{n+1}<M>``), hence stabilize.

    ``phi(M)`` is the smallest ``m`` with ``r_n = r_m`` for ALL ``n >= m`` -- i.e. the
    index of the LAST strict decrease. NOTE: this is NOT "the first ``n`` with
    ``r_n = r_{n+1}``": ``L`` injective on ``L^n<M>`` does NOT force injectivity on
    ``L^{n+1}<M>`` (that subgroup need not sit inside ``L^n<M>``), so the sequence can
    read ``1, 1, 0`` -- e.g. ``S_1`` over ``kA_3/rad^2``: ``Omega S_1 = S_2`` (rank 1),
    ``Omega^2 S_1 = P_3`` projective (rank 0), and ``phi(S_1) = pd(S_1) = 2``, not 0.

    Termination is rigorous. (a) When every syzygy has become projective/zero the rank
    is 0 forever (finite projective dimension). (b) Fitting: once the registry of
    distinct non-projective indecomposable classes stops growing, ``L`` is an
    endomorphism of the (now Omega-closed) free group they span, and for an
    endomorphism of a free group of rank ``g`` the sequence ``rank(L^n<M>)`` is constant
    for ``n >= g`` (``L`` is injective on the stabilized image ``im L^g``); so once the
    registry has been unchanged for ``len(reps)+1`` consecutive steps no further drop
    can occur. ``bound`` caps the search and RAISES loudly if neither certificate is
    reached (never a guessed value)."""
    K = _K0(budget)
    seq = [S for S, _ in decompose(M, budget=budget) if not _is_projective(S)]
    ranks = [K.rank(seq)]
    reps_at = [len(K.reps)]
    stabilized = not seq
    for n in range(1, bound + 1):
        seq = [Y for X in seq for Y in (syzygy(X),) if Y.dim]
        ranks.append(K.rank(seq))
        reps_at.append(len(K.reps))
        if not seq:                          # (a) finite pd: rank is 0 forever after
            stabilized = True
            break
        w = len(K.reps) + 1                   # (b) Fitting closure window
        if n + 1 >= w and reps_at[-1] == reps_at[-w]:
            stabilized = True
            break
    if not stabilized:
        raise QuiverlabError(
            f"igusa_todorov_phi: rank did not stabilize within depth {bound}",
            hint="raise `bound`; a genuine non-stabilization indicates a K0 bug or a "
                 "module whose syzygies never enter a finite Omega-closed support")
    phi = 0
    for i in range(1, len(ranks)):            # least m with r_n == r_m for all n >= m
        if ranks[i] < ranks[i - 1]:           # == the index of the last strict drop
            phi = i
    return phi


def igusa_todorov_psi(M, budget=512, bound=64):
    """The Igusa-Todorov function ``psi(M) = phi(M) + fpd(Omega^{phi(M)} M)``, where
    ``fpd(N) = max{ pd(Y) : Y a summand of N with pd(Y) < infinity }`` (0 if none)
    (Igusa-Todorov 2005). For finite projective dimension ``psi(M) = phi(M) = pd(M)``.
    Inherits ``decompose``'s loud char-caveat refusal."""
    phi = igusa_todorov_phi(M, budget=budget, bound=bound)
    W = M
    for _ in range(phi):
        W = syzygy(W)
    fpd = 0
    for Y, _ in decompose(W, budget=budget):
        pdY = Y.projective_resolution(bound).pd()
        if pdY is not None:                   # only finite-pd summands enter fpd
            fpd = max(fpd, pdY)
    return phi + fpd


# ---------------------------------------------------------------------------
# Dominant dimension (leading projective-injective coresolvents of the regular
# module; self-injective => infinity)
# ---------------------------------------------------------------------------
def _regular_module(A, side="right"):
    """The regular module ``A_A = (+)_v P_v`` (Plan-37 ``direct_sum``)."""
    from quiverlab.modules.morphism import direct_sum
    Ps = [A.projective(v, side=side) for v in A.quiver.vertices]
    D, _, _ = direct_sum(*Ps)
    return D


@dataclass
class DominantDimension:
    """dom.dim A, honest: an exact leading-projective count, a certified lower bound
    (coresolution not resolved within depth), or a certified ``infinite`` (A self-
    injective -- every injective coresolvent of the regular module is projective)."""
    value: "int | None"
    exact: bool
    infinite: bool
    _bound: int = 32

    def __int__(self):
        if self.value is None:
            raise QuiverlabError("dominant dimension is infinite; it has no int value")
        return self.value

    def __eq__(self, other):
        if isinstance(other, DominantDimension):
            return ((self.value, self.exact, self.infinite)
                    == (other.value, other.exact, other.infinite))
        if isinstance(other, int):
            return self.exact and not self.infinite and self.value == other
        return NotImplemented

    def __repr__(self):
        if self.infinite:
            return ("dom.dim = infinity (self-injective; every injective coresolvent "
                    "of A is projective)")
        if self.exact:
            return f"dom.dim = {self.value}"
        return (f">= {self.value} (certified lower bound; not resolved within depth "
                f"{self._bound})")


def dominant_dimension(A, bound=32):
    """dom.dim A = the index of the first term in a minimal injective coresolution of
    the regular right module ``A_A = (+)_v P_v`` that is NOT projective (``infinite``
    iff every such term is projective, iff A is self-injective) (spec section 3.5;
    Assem-Simson-Skowronski)."""
    from quiverlab.modules.ext import is_selfinjective
    from quiverlab.modules.injective import injective_resolution
    if is_selfinjective(A):
        return DominantDimension(None, exact=False, infinite=True, _bound=bound)
    reg = _regular_module(A)
    res = injective_resolution(reg, bound)
    count = 0
    for n in range(bound + 1):
        term = res.terms[n] if n < len(res.terms) else None
        if term is None or term.dim == 0:                 # coresolution ended proj.
            return DominantDimension(count, exact=True, infinite=False, _bound=bound)
        if term.projective_resolution(1).pd() == 0:        # E^n projective: it counts
            count += 1
        else:
            return DominantDimension(count, exact=True, infinite=False, _bound=bound)
    return DominantDimension(count, exact=False, infinite=False, _bound=bound)  # bound


# ---------------------------------------------------------------------------
# Gorenstein dimension + is_gorenstein (both-sided injective dimension of the
# regular module; three-valued True/None -- never a bare False)
# ---------------------------------------------------------------------------
def _regular_injective_dimension(A, bound):
    from quiverlab.modules.injective import injective_dimension
    return injective_dimension(_regular_module(A), bound=bound)


@dataclass
class GorensteinDimension:
    """The (Iwanaga-)Gorenstein data of A: the injective dimension of the regular
    module on the right (``A_A``) and left (``_A A``) sides. ``is_gorenstein`` is
    three-valued True/None: True iff BOTH sides resolve finite; None when either is a
    mere lower bound -- the bounded engine never proves an infinite injective
    dimension, so a bare ``False`` is never emitted (Plan 40 honesty rule)."""
    right_id: "int | None"
    left_id: "int | None"
    is_gorenstein: "bool | None"
    _bound: int = 32

    def __repr__(self):
        if self.right_id is not None and self.left_id is not None:
            return (f"Gorenstein: right inj.dim {self.right_id}, "
                    f"left inj.dim {self.left_id}")
        return (f"undecided within depth {self._bound} (an injective dimension did not "
                "resolve; infinity is not proven)")


def gorenstein_dimension(A, bound=32):
    """A is (Iwanaga-)Gorenstein iff the right AND left injective dimensions of the
    regular module are both finite. ``is_gorenstein`` is True when both resolve within
    ``bound``, else None (never a bare False -- see the honesty note) (spec section
    3.5; Assem-Simson-Skowronski)."""
    right = _regular_injective_dimension(A, bound)
    left = _regular_injective_dimension(A.opposite(), bound)
    both_finite = right is not None and left is not None
    verdict = True if both_finite else None            # never a bare False
    return GorensteinDimension(right, left, verdict, _bound=bound)


def is_gorenstein(A, bound=32):
    """Three-valued Gorenstein verdict: True (both injective dimensions finite) or None
    (an injective dimension did not resolve within ``bound``; infinity is not proven --
    never False) (Plan 40)."""
    return gorenstein_dimension(A, bound).is_gorenstein


# ---------------------------------------------------------------------------
# Omega- and tau-periodicity certificates (is_isomorphic-certified)
# ---------------------------------------------------------------------------
def omega_periodicity(M, max_period=12, bound=64):
    """The least ``k`` in ``1..max_period`` with ``Omega^k M ~ M`` (is_isomorphic-
    certified), else ``None`` -- including when some ``Omega^i M = 0`` (finite
    projective dimension => not Omega-periodic). Raises the ``is_isomorphic`` loud
    refusal unchanged when an iso comparison is undecidable (Plan 40)."""
    if M.dim == 0 or _is_projective(M):
        return None
    cur = M
    for k in range(1, max_period + 1):
        cur = syzygy(cur)
        if cur.dim == 0:                     # finite projective dimension
            return None
        if cur.dim == M.dim and is_isomorphic(cur, M):   # loud if undecidable
            return k
    return None


def tau_periodicity(M, max_period=12):
    """The least ``k`` in ``1..max_period`` with ``tau^k M ~ M`` (is_isomorphic-
    certified), else ``None`` (a ``tau^i M = 0`` => the tau-orbit terminates => not
    periodic). Raises the ``is_isomorphic`` loud refusal unchanged when undecidable
    (Plan 40)."""
    if M.dim == 0 or _is_projective(M):
        return None
    cur = M
    for k in range(1, max_period + 1):
        cur = cur.tau()
        if cur.dim == 0:                     # tau-orbit terminated (hit a projective)
            return None
        if cur.dim == M.dim and is_isomorphic(cur, M):
            return k
    return None


# ---------------------------------------------------------------------------
# Finitistic-dimension bounds (rigorous lower; gl.dim upper when finite, honest
# degrade otherwise)
# ---------------------------------------------------------------------------
@dataclass
class FinitisticBounds:
    """findim A = sup{ pd N : pd N < infinity }, bracketed honestly. ``lower`` is a
    genuine lower bound (a finite pd actually found); ``upper`` is gl.dim when finite
    (findim = gl.dim then) or ``None`` (honest degrade -- no folklore number). ``exact``
    iff ``lower == upper`` both finite."""
    lower: int
    upper: "int | None"
    exact: bool
    note: str

    def __repr__(self):
        if self.exact:
            return f"findim = {self.lower}"
        if self.upper is not None:
            return f"findim in [{self.lower}, {self.upper}]"
        return f">= {self.lower} (upper bound undetermined)"


def _finite_pd_probe_lower(A, bound):
    """Max finite pd over ``{ S_v } U { Omega S_v } U { radical layers of P_v }`` -- a
    rigorous lower bound: any finite pd found is a valid ``findim`` witness. The simples
    are included, so this reaches ``gl.dim`` exactly whenever ``gl.dim`` is finite."""
    lower = 0
    probes = []
    for v in A.quiver.vertices:
        Sv = A.simple(v)
        probes.append(Sv)
        probes.append(syzygy(Sv))
        layer = A.projective(v)                # walk rad^k P_v until zero
        while layer.dim:
            probes.append(layer)
            layer = layer.radical()
    for N in probes:
        if N.dim == 0:
            continue
        pd = N.projective_resolution(bound).pd()
        if pd is not None:                     # only FINITE pd enters the lower bound
            lower = max(lower, pd)
    return lower


def _igusa_todorov_finitistic_upper(A, bound):
    """The Igusa-Todorov psi-finitistic UPPER bound -- HONEST-DEGRADED to ``None``.

    THEOREM PINNED (Igusa-Todorov, "On the finitistic global dimension conjecture for
    Artin algebras", Fields Inst. Commun. 45 (2005), 201-204). For a short exact
    sequence ``0 -> A -> B -> C -> 0`` of f.d. modules with ``pd C < infinity``,
    ``pd C <= psi(A (+) B) + 1``. Applied to the syzygy sequence
    ``0 -> Omega M -> P -> M -> 0`` (``P`` a projective cover) of any FINITE-pd ``M``,
    and using ``psi(X (+) projective) = psi(X)``, this gives the genuine PER-MODULE
    bound ``pd M <= psi(Omega M) + 1`` (constant ``+1``, from the one-term syzygy
    sequence -- this is where the additive constant is fixed by the theorem itself).

    WHY THE AGGREGATE ``psi((+)_v Omega S_v) + 1`` IS *NOT* SHIPPED AS ``findim``'s upper
    bound. Bounding ``findim = sup{ pd M : pd M < infinity }`` needs ``sup_M psi(Omega
    M)``, and ``psi(Omega M)`` for an arbitrary finite-pd ``M`` is NOT controlled by
    ``psi((+)_v Omega S_v)``: ``Omega M`` need not lie in ``add((+)_v Omega S_v)`` (a
    general syzygy is not built from the syzygies of the simples). More decisively, a
    finite GENERAL upper bound for ``findim`` computed from the presentation would
    resolve the finitistic dimension conjecture (findim ``< infinity`` for every Artin
    algebra), which is OPEN. So no such certified finite bound exists for a general
    algebra with infinite global dimension; a specific ``psi(...) + const`` number here
    would be folklore, exactly what the house honesty rule forbids -- so the constant is
    NOT "arbitrated" into a shipped number, the whole aggregate is degraded.

    Hence this returns ``None`` (honest degrade). The only certified finite upper bound
    this surface ships is ``gl.dim`` when it is finite (``findim = gl.dim`` then), in
    :func:`finitistic_dimension_bounds`. A successor plan that supplies a certified
    finite-representation-dimension witness ``V`` (so ``add V`` contains every relevant
    syzygy) can then ship ``psi(V) + 1`` as a genuine bound and flip this degrade."""
    return None


def finitistic_dimension_bounds(A, bound=32):
    """``findim A`` bracketed honestly (Plan 40). Lower bound: the max finite pd over
    ``{S_v} U {Omega S_v} U {rad-layers of P_v}`` (rigorous). Upper bound: ``gl.dim``
    when exact-finite (``findim = gl.dim``, ``exact=True``); otherwise ``None`` (the
    Igusa-Todorov psi-bound is not a certifiable general theorem -- see
    :func:`_igusa_todorov_finitistic_upper`). A numeric ``upper`` is ALWAYS ``>= lower``
    (a violation is a mis-implementation -- raised, never clamped)."""
    from quiverlab.modules.ext import global_dimension
    lower = _finite_pd_probe_lower(A, bound)
    g = global_dimension(A, bound=bound)
    if g.exact:
        upper = g.value
        # findim <= gl.dim, equality when gl.dim finite; the simple probes make lower
        # >= max_v pd(S_v) = gl.dim, so lower == upper == gl.dim here.
        assert upper >= lower, "finitistic lower bound exceeded gl.dim (bug)"
        return FinitisticBounds(lower, upper, exact=True,
                                note="gl.dim exact and finite => findim = gl.dim")
    upper = _igusa_todorov_finitistic_upper(A, bound)   # int or None (None here)
    if upper is not None and upper < lower:
        raise QuiverlabError(                           # the mandated sanity gate
            "finitistic upper bound < lower bound: the Igusa-Todorov bound is "
            "mis-implemented for this presentation")
    return FinitisticBounds(
        lower, upper, exact=False,
        note=("Igusa-Todorov psi-bound" if upper is not None
              else "upper bound undetermined (Igusa-Todorov psi-bound not certified "
                   "for this presentation)"))
