# SPDX-License-Identifier: MIT
# Generalized from the bridge lab engine `obstruction/module_ext.py` (unlicensed in the
# bank; lifted here with attribution under quiverlab's MIT license per spec section 9).
# The bank engine was hardcoded to a 4-vertex diamond over Q; this reimplementation runs
# over ANY vertex set and ANY exact Domain via fields.linalg.
"""Minimal projective resolutions of right A-modules by iterated projective covers
(Green-Solberg-Zacharia, Trans. AMS 353 (2001) 2915-2939), spec section 5 component 7.

Right modules; left-to-right composition. A minimal resolution
  ... -> Q_2 -> Q_1 -> Q_0 -> M -> 0
is built one step at a time: cover M by projectives generated by top M, take the syzygy
kernel, cover it, repeat. Minimality = generators chosen independent modulo the radical,
so d_n(Q_n) subset rad Q_{n-1} and the betti numbers are the true Betti numbers."""
from quiverlab.errors import DepthLimitError
from quiverlab.modules import linalg_mod as lm
from quiverlab.modules.builders import projective
from quiverlab.modules.radtopsoc import submodule, _rad_image_cols

_GUARD_HINT = ("module resolution term blew past max_term_dim; the certified length is "
               "in the message. Raise max_term_dim to push deeper.")


def _direct_sum(modules, name="Q"):
    """Block-diagonal direct sum of Modules (all over the same algebra); returns the sum
    Module plus the list of (start, dim) offsets of each summand."""
    if not modules:
        return None, []
    A = modules[0].algebra
    dom = A.domain
    dims = [m.dim for m in modules]
    n = sum(dims)
    offs = []
    o = 0
    for d in dims:
        offs.append((o, d))
        o += d
    action = {}
    for label in modules[0].action:
        M = lm.zeros(n, n, dom)
        for (s, d), mod in zip(offs, modules):
            blk = mod.action[label]
            for i in range(d):
                for j in range(d):
                    M[s + i][s + j] = blk[i][j]
        action[label] = M
    from quiverlab.modules.module import Module
    Q = Module(A, n, action, name=name)
    Q._summand_vertices = [m._pv_vertex for m in modules]
    return Q, offs


def _homogeneous_top_generators(M):
    """A k-basis of top M, each lifted to a column of M living in a single vertex block.
    Returns list of (vertex, column-in-M). These are the projective-cover generators."""
    dom = M.domain
    rad_cols = _rad_image_cols(M)
    gens = []
    ident = lm.identity(M.dim, dom)
    for v in M.algebra.quiver.vertices:
        Pv = M.vertex_projection(v)                       # image = M*e_v
        # candidate vectors spanning M*e_v: independent columns of the projection
        piv = lm.column_space_pivots(Pv, dom)
        cands = [lm.col(Pv, j) for j in piv]
        # keep those independent modulo rad M (+ already-chosen gens): mod-radical basis
        chosen = lm.independent_modulo(cands, rad_cols + [g[1] for g in gens], dom)
        for idx in chosen:
            gens.append((v, cands[idx]))
    return gens


def projective_cover(M):
    """Q0 = (+)_g P_{vertex(g)} with cover d0: Q0 -> M sending each summand's canonical
    generator (the e_v basis vector of P_v) to the lifted top-generator g."""
    dom = M.domain
    gens = _homogeneous_top_generators(M)
    summands = [projective(M.algebra, v) for (v, _) in gens]
    Q0, offs = _direct_sum(summands, name="Q0") if summands else (None, [])
    if Q0 is None:
        from quiverlab.modules.module import Module
        Q0 = Module(M.algebra, 0, {lab: lm.zeros(0, 0, dom) for lab in M.action}, name="Q0")
    # cover matrix: column = image in M of each Q0 basis vector b = (canonical gen)*path.
    # For summand P_v with generator g (a column of M), the P_v basis vector indexed by
    # path label p (source v) maps to g * p = action_M[p] @ g.
    cols = []
    for (v, g), (s, d), Pmod in zip(gens, offs, summands):
        for k in range(d):
            plabel = Pmod._pv_basis_labels[k]              # label of the k-th P_v basis path
            img = lm.matvec(M.action[plabel], g, dom)      # g * p
            cols.append(img)
    d0 = lm.cols_to_matrix(cols) if cols else lm.zeros(M.dim, 0, dom)
    return Q0, d0, gens


def minimal_resolution(M, length, max_term_dim=200000):
    terms, dmats = [], []
    Q0, d0, _ = projective_cover(M)
    terms.append(_term_data(Q0))
    dmats.append(d0)
    cur_mod, cur_map = Q0, d0            # cur_map : cur_mod -> (previous)
    for n in range(1, length + 1):
        # syzygy Omega_n = ker(cur_map) as a submodule of cur_mod
        ker_cols = lm.kernel_columns(cur_map, M.domain) if cur_map and cur_map[0] else \
            ([lm.col(lm.identity(cur_mod.dim, M.domain), j) for j in range(cur_mod.dim)]
             if cur_mod.dim else [])
        if not ker_cols:
            terms.append(_term_data(None))
            dmats.append(lm.zeros(cur_mod.dim, 0, M.domain))
            break
        Omega = submodule(cur_mod, ker_cols, name=f"Omega_{n}")
        if Omega.dim > max_term_dim:
            raise DepthLimitError(
                f"module resolution: syzygy dim {Omega.dim} exceeds max_term_dim="
                f"{max_term_dim}; certified through length {n - 1}", hint=_GUARD_HINT)
        Qn, cover, _ = projective_cover(Omega)
        # d_n : Q_n -> Q_{n-1} is (cover: Q_n -> Omega) then (inclusion Omega -> Q_{n-1})
        B = lm.cols_to_matrix(ker_cols)                    # Omega basis inside cur_mod
        dn = lm.matmul(B, cover, M.domain) if cover and cover[0] else \
            lm.zeros(cur_mod.dim, 0, M.domain)
        terms.append(_term_data(Qn))
        dmats.append(dn)
        cur_mod, cur_map = Qn, cover
        if Qn.dim == 0:
            break
    return terms, dmats


class _term_data:
    def __init__(self, Qn):
        self.module = Qn
        self.vertices = list(getattr(Qn, "_summand_vertices", [])) if Qn else []
        self.dim = Qn.dim if Qn else 0


class ProjectiveResolution:
    def __init__(self, M, terms, dmats):
        self.module = M
        self.terms = terms
        self.dmats = dmats
        self.length = len(terms)

    def term(self, n):
        return self.terms[n].vertices if n < len(self.terms) else []

    def betti(self, n):
        return len(self.term(n))

    def differential(self, n):
        return self.dmats[n] if n < len(self.dmats) else []

    def dimension_vectors(self):
        return [t.module.dimension_vector() if t.module else {} for t in self.terms]

    def is_finite(self):
        return any(t.dim == 0 for t in self.terms)

    def pd(self):
        for n, t in enumerate(self.terms):
            if t.dim == 0:
                return n - 1
        return None                     # not resolved within the requested length

    def __repr__(self):
        parts = " <- ".join(
            "(+)".join(f"P_{v}" for v in t.vertices) if t.vertices else "0"
            for t in self.terms)
        return f"proj. res. of {self.module.name}: {parts}"
