"""The Avella-Alaminos-Geiss (AG) derived invariant of a gentle algebra (Plan 46 / C5).

For a gentle algebra ``A = kQ/I`` (``I`` generated by length-2 monomials) AAG 2008
attach a MULTISET of pairs ``(n, m) in N x N``, a DERIVED invariant: derived-equivalent
gentle algebras share it (AAG 2008, Theorem A). It is honestly **NOT complete** --
completeness needs the graded Opper-Plamondon-Schroll geometric data, out of scope
here; never claim it separates all derived-equivalence classes.

Threads (partition ``Q_1``):
  - a *permitted thread* is a maximal NONZERO directed path (``c_i c_{i+1} not in I``);
    gentle => the permitted successor of each arrow is unique, so permitted threads
    partition ``Q_1``.
  - a *forbidden thread* (antipath) is a maximal path of RELATIONS
    (``c_i c_{i+1} in I``), maximal; gentle => partition ``Q_1`` too. A forbidden
    thread may be CYCLIC (self-injective case, e.g. ``...abab...``).

Algorithm (Asashiba's blossoming form of AAG, as in Nakaoka arXiv:1811.00775 Def
2.7-2.11 -- verified to reproduce that paper's Example 2.15 tabulated value
``{(3,2),(2,2),(0,3)}`` exactly):
  - Blossom ``(Q, I)`` to ``(Q^*, I^*)`` so every original vertex has in- and
    out-degree 2 (add source/sink blossom arrows), completing the permitted matching
    ``M_p`` and the complementary forbidden matching ``M_f`` (perfect matchings
    in-arrows -> out-arrows at each vertex).
  - Each source blossom seeds a maximal permitted path ``P_p = sigma_p wp_p tau_p``.
    Following ``M_f`` backward from ``tau_p`` reaches a source blossom ``sigma_{Phi(p)}``:
    this is the AAG permutation ``Phi``. An orbit ``O`` of ``Phi`` has type
    ``(n, m) = (|O|, sum of forbidden-thread lengths in O)``.
  - A cyclic forbidden thread not touching a blossom contributes ``(0, length)``.

``sum n = 2|Q_0| - |Q_1|`` (the number of permitted threads ``d_A``) and
``sum m = |Q_1|`` (every arrow lies in exactly one forbidden thread). The ``(n, m)``
order is (permitted, forbidden), the AAG / Nakaoka convention. Float-free / exact."""
from __future__ import annotations

from dataclasses import dataclass

from quiverlab.errors import QuiverlabError
from quiverlab.invariants.recognizers import _len2_in_ideal, is_gentle
from quiverlab.resolutions_cs.build import reduction_system_of


def _require_gentle(A):
    if A.quiver is None or A.relations is None:
        raise QuiverlabError("ag: need a quiver-presented gentle algebra",
                             hint="build the algebra via Quiver.algebra(...)")
    if not is_gentle(A):
        raise QuiverlabError(
            "ag: the AG invariant is defined for GENTLE algebras only",
            hint="is_gentle(A) is False; gentle = special-biserial with I generated "
                 "by length-2 paths and the dual biserial condition")


# ---------------------------------------------------------------------------
# Successor maps + threads (partition Q_1)
# ---------------------------------------------------------------------------


def _succ_maps(A):
    """(p_succ, p_pred, f_succ, f_pred): arrow-name -> arrow-name partial maps.
    ``p_succ[a]`` = unique ``b`` with ``s(b)=t(a)``, ``a*b not in I``; ``f_succ`` its
    zero counterpart. Predecessors dually. Gentle => each is a partial injection."""
    Q = A.quiver
    rs = reduction_system_of(A)
    p_succ, p_pred, f_succ, f_pred = {}, {}, {}, {}
    for a in Q.arrows:
        ta = Q.target(a)
        for b in Q.arrows:
            if Q.source(b) == ta:
                if _len2_in_ideal(rs, a, b):
                    f_succ[a] = b
                    f_pred[b] = a
                else:
                    p_succ[a] = b
                    p_pred[b] = a
    return p_succ, p_pred, f_succ, f_pred


def _threads(arrows, succ, pred):
    """Maximal chains under the partial map ``succ`` (with predecessor ``pred``);
    handles cyclic orbits. Returns a list of arrow-name tuples partitioning ``arrows``."""
    seen = set()
    threads = []
    for a in arrows:
        if a in seen:
            continue
        # walk back to a start (or detect a cycle)
        start = a
        guard = 0
        while pred.get(start) is not None and pred[start] != a and guard <= len(arrows):
            start = pred[start]
            guard += 1
        cyclic = pred.get(start) == a          # closed loop back to a
        chain = []
        cur = start
        while cur is not None and cur not in seen:
            seen.add(cur)
            chain.append(cur)
            cur = succ.get(cur)
        threads.append(tuple(chain))
    return threads


def permitted_threads(A):
    """Maximal nonzero directed paths (permitted threads), as arrow-name tuples.
    Partition ``Q_1`` (gentle)."""
    _require_gentle(A)
    p_succ, p_pred, _f, _fp = _succ_maps(A)
    return _threads(list(A.quiver.arrows), p_succ, p_pred)


def forbidden_threads(A):
    """Maximal paths of relations (forbidden threads / antipaths), as arrow-name
    tuples. Partition ``Q_1`` (gentle); a cyclic forbidden thread is one tuple."""
    _require_gentle(A)
    _p, _pp, f_succ, f_pred = _succ_maps(A)
    return _threads(list(A.quiver.arrows), f_succ, f_pred)


# ---------------------------------------------------------------------------
# Blossoming + the AAG permutation
# ---------------------------------------------------------------------------


def _blossom_matchings(A):
    """Permitted / forbidden perfect matchings ``M_p, M_f`` (in-arrow -> out-arrow)
    on the blossomed in/out sets at every original vertex. Blossom arrow names:
    ``S{v}_{i}`` (source-in), ``T{v}_{i}`` (sink-out)."""
    Q = A.quiver
    rs = reduction_system_of(A)
    orig = set(Q.arrows)

    def nonzero(a, b):
        return not _len2_in_ideal(rs, a, b)

    Mp, Mf = {}, {}
    for v in Q.vertices:
        ins = [a for a in Q.arrows if Q.target(a) == v]
        outs = [a for a in Q.arrows if Q.source(a) == v]
        i = 0
        while len(ins) < 2:
            ins.append(f"S{v}_{i}")
            i += 1
        j = 0
        while len(outs) < 2:
            outs.append(f"T{v}_{j}")
            j += 1
        m1 = {ins[0]: outs[0], ins[1]: outs[1]}
        m2 = {ins[0]: outs[1], ins[1]: outs[0]}

        def permitted_ok(m):
            return all(nonzero(a, g) for a, g in m.items()
                       if a in orig and g in orig)

        def forbidden_ok(m):
            return all(not nonzero(a, g) for a, g in m.items()
                       if a in orig and g in orig)

        if permitted_ok(m1) and forbidden_ok(m2):
            mp, mf = m1, m2
        elif permitted_ok(m2) and forbidden_ok(m1):
            mp, mf = m2, m1
        elif permitted_ok(m1):
            mp, mf = m1, m2
        elif permitted_ok(m2):
            mp, mf = m2, m1
        else:
            mp, mf = m1, m2                     # all-blossom vertex: either is fine
        Mp.update(mp)
        Mf.update(mf)
    return Mp, Mf, orig


def _is_blossom_in(nm):
    return isinstance(nm, str) and nm.startswith("S")


def _is_blossom_out(nm):
    return isinstance(nm, str) and nm.startswith("T")


def _is_blossom(nm):
    return _is_blossom_in(nm) or _is_blossom_out(nm)


# ---------------------------------------------------------------------------
# The invariant
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class AGInvariant:
    """The AG invariant: a MULTISET of ``(n, m)`` pairs (sorted). ``n`` counts the
    permitted threads in an AAG-orbit, ``m`` the forbidden-thread arrows; a cyclic
    forbidden thread gives ``(0, m)``. A DERIVED invariant, honestly NOT complete."""
    pairs: tuple

    def as_multiset(self):
        out = {}
        for p in self.pairs:
            out[p] = out.get(p, 0) + 1
        return out


def ag_invariant(A) -> AGInvariant:
    """The Avella-Alaminos-Geiss derived invariant of the gentle algebra ``A``.
    Loud on non-gentle input. DERIVED-INVARIANT, NOT COMPLETE (documented)."""
    _require_gentle(A)
    Mp, Mf, orig = _blossom_matchings(A)
    source_blossoms = [a for a in Mp if _is_blossom_in(a)]

    # permitted path from each source blossom: follow M_p to a sink blossom
    ends = {}          # source blossom -> ending blossom-out tau
    for s in source_blossoms:
        cur = s
        while True:
            nxt = Mp[cur]
            if _is_blossom_out(nxt):
                ends[s] = nxt
                break
            cur = nxt

    # antipath ending at tau_p: follow M_f backward to a source blossom = Phi(p);
    # count the original arrows crossed (the forbidden-thread length delta_p)
    Mf_inv = {out: inp for inp, out in Mf.items()}
    Phi, anti_len = {}, {}
    for s in source_blossoms:
        cur = ends[s]
        length = 0
        while True:
            pred = Mf_inv[cur]
            if _is_blossom_in(pred):
                Phi[s] = pred
                break
            length += 1
            cur = pred
        anti_len[s] = length

    # orbits of Phi -> pairs (|orbit|, sum forbidden lengths)
    pairs = []
    seen = set()
    for s in source_blossoms:
        if s in seen:
            continue
        orbit = []
        cur = s
        while cur not in seen:
            seen.add(cur)
            orbit.append(cur)
            cur = Phi[cur]
        n = len(orbit)
        m = sum(anti_len[t] for t in orbit)
        pairs.append((n, m))

    # cyclic forbidden threads (anticycles) -> (0, length)
    seen2 = set()
    for a in orig:
        if a in seen2:
            continue
        cyc, cur, cyclic = [], a, True
        while True:
            cyc.append(cur)
            seen2.add(cur)
            nxt = Mf.get(cur)
            if nxt is None or _is_blossom(nxt):
                cyclic = False
                break
            if nxt == a:
                break
            if nxt in seen2:
                cyclic = False
                break
            cur = nxt
        if cyclic:
            pairs.append((0, len(cyc)))

    return AGInvariant(tuple(sorted(pairs)))
