# Ported from hanlab (HansConjecture, MIT (c) 2026 Marco Armenta,
# github.com/marcoarmenta/hansconjecture), bank state of 2026-07-12.
# Mechanical changes only: package-relative imports, __main__ blocks removed,
# float literals eradicated (quiverlab AST gate), env guard renamed.
"""Bardzell's minimal projective A^e-bimodule resolution for MONOMIAL algebras.

A monomial algebra A = kQ/I (I generated by paths/monomials) admits the minimal
projective bimodule resolution of Bardzell (1997, "The alternating syndrome of a
monomial algebra"; see also Skoldberg, and Redondo--Roman). This module exposes it
as a homology-only `Resolution` backend, `BardzellResolution`, cross-checked exactly
against the normalized-bar-complex oracle (hanlab.homology_dims) and reaching depths
far past the bar complex's combinatorial blow-up.

------------------------------------------------------------------------------
THE MATH (what is implemented)
------------------------------------------------------------------------------
Let A = kQ/I be monomial with vertex set Q_0, arrow set Q_1, and minimal generating
set R of relations (each a path of length >= 2). Bardzell's "associated paths"
(equivalently Anick's n-chains / n-ambiguities) are graded sets AP^n:

  * AP^0 = Q_0 (vertices)
  * AP^1 = Q_1 (arrows)
  * AP^2 = R   (the minimal relations)
  * AP^n (n >= 2): a path p admits a LEFT DECOMPOSITION  p = u_0 u_1 ... u_{n-1}
    into n nonempty blocks with u_0 an arrow, such that for every consecutive pair,
        u_{k} u_{k+1} in I   and   no proper suffix of u_k u_{k+1} lies in I,
    i.e. u_k u_{k+1} is exactly a minimal relation. This is Bardzell's overlap/chain
    condition: each relation overlaps the next, the chain covering p exactly. For
    these algebras the decomposition is unique.

The projective bimodule resolution is
        P_n = (+)_{p in AP^n}  A e_{o(p)} (x) e_{t(p)} A,
where o(p) = source(p), t(p) = target(p). Applying  A (x)_{A^e} -  collapses each
summand to e_{o(p)} A e_{t(p)} = { paths w : t(p) -> o(p) in A } ("loops closing p").
So the n-th term of the reduced complex has basis

        C_n = { (p, w) : p in AP^n,  w a nonzero path  t(p) -> o(p) in A }.

THE REDUCED DIFFERENTIAL d_n : C_n -> C_{n-1} alternates (Bardzell's alternating
formula, pushed through A (x)_{A^e} -):

  n == 1  (arrows -> vertices):
        d_1(x, w) = (t(x); w.x)  -  (o(x); x.w)
     (the commutator/augmentation map; on a single loop these cancel iff the loop
      commutes with the arrow -- giving HH_0 = A/[A,A]).

  n even >= 2  ("big" map): for each (n-1)-associated path q occurring as a subpath
        p = pre . q . suf,
        d_n(p, w)  +=  ( q ;  suf . w . pre )       (summed over all occurrences).

  n odd >= 3  ("small" map): with the unique decomposition p = u_0 u_1 ... u_{n-1},
        P = u_1 ... u_{n-1}   (drop first block; p = u_0 . P),
        Q = u_0 ... u_{n-2}   (drop last block;  p = Q . u_{n-1}),
        d_n(p, w)  =  ( P ;  w . u_0 )  -  ( Q ;  u_{n-1} . w ).

Loop composition is in path order and the result is reduced mod I (a product that
runs through a relation, or fails to compose, is zero). Integer entries are kept
UN-REDUCED mod p, so small primes (e.g. p | something in the boundary) carry signal.

------------------------------------------------------------------------------
VERIFIED (exact agreement with the bar-complex oracle, primes 32003,2,3,5)
------------------------------------------------------------------------------
  * k[x]/(x^a)         (one vertex, one loop x, relation x^a)      a in {2,3,4,...}
  * cyclic Nakayama    kZ_n / rad^ell (n-cycle, length-ell relations)
  * local_3gen_radsq   (one vertex, 3 loops, all length-2 relations) -- the richest
                        monomial test; reproduces the oracle [4,6,14,32,...] (char 0)
                        and [4,9,17,35,...] (p = 2), and unlocks depth N >= 20.

These cover the single-cycle (truncated polynomial / cyclic Nakayama) and the
radical-square-zero overlap families, and the GENERAL overlap chains (cyclic
Nakayama with ell > 2, where relations overlap nontrivially) -- all oracle-exact.

------------------------------------------------------------------------------
SCOPE / FUTURE WORK
------------------------------------------------------------------------------
The differential above is implemented and verified for the families listed. The
general-overlap big/small alternation is implemented exactly as Bardzell's formula
and validated on overlapping relations (cyclic Nakayama ell > 2). A residual
direction is a careful audit of SIGNS for monomial algebras whose quiver has several
vertices with branching loops at a single vertex of mixed even/odd relation lengths,
which the present test families do not exercise; for the verified families the maps
are sign-correct (exact agreement on all primes, all overlap degrees).
"""

import numpy as np

from quiverlab.engine.resolutions import Resolution


# ----------------------------------------------------------------------
# Monomial presentation A = kQ/I
# ----------------------------------------------------------------------
class MonomialPresentation:
    """A monomial algebra as a quiver Q with a minimal set of monomial relations.

    Parameters
    ----------
    vertices : list of hashable vertex labels.
    arrows   : list of (arrow_id, source, target); arrow_id any hashable (typically
               an int), source/target in `vertices`. Paths are tuples of arrow_ids.
    relations: list of paths (tuples of arrow_ids), each of length >= 2, forming a
               MINIMAL generating set of the ideal I (no relation a subpath of
               another, no proper suffix of a relation lying in I).

    Convenience builders (matching hanlab's monomial test algebras):
        MonomialPresentation.truncated_polynomial(a)   -> k[x]/(x^a)
        MonomialPresentation.cyclic_nakayama(n, ell)    -> kZ_n / rad^ell
        MonomialPresentation.local_radsq(g)             -> g-loop local, rad^2 = 0
    """

    def __init__(self, vertices, arrows, relations):
        self.vertices = list(vertices)
        self.arrows = [tuple(a) for a in arrows]
        self.src = {a: s for (a, s, t) in self.arrows}
        self.tgt = {a: t for (a, s, t) in self.arrows}
        self.relations = [tuple(r) for r in relations]
        self.relset = set(self.relations)
        self.bysrc = {}
        for (a, s, t) in self.arrows:
            self.bysrc.setdefault(s, []).append(a)
        self.maxrel = max((len(r) for r in self.relations), default=0)

    # -- builders ------------------------------------------------------
    @staticmethod
    def truncated_polynomial(a):
        """k[x]/(x^a): one vertex, one loop x, relation x^a."""
        return MonomialPresentation(["v"], [(0, "v", "v")], [tuple([0] * a)])

    @staticmethod
    def cyclic_nakayama(n, ell):
        """kZ_n/rad^ell: n vertices in a cycle 0->1->...->(n-1)->0, arrow i: i->i+1,
        relations = all paths of length ell."""
        arrows = [(i, i, (i + 1) % n) for i in range(n)]
        rels = [tuple((i + k) % n for k in range(ell)) for i in range(n)]
        return MonomialPresentation(list(range(n)), arrows, rels)

    @staticmethod
    def local_radsq(g):
        """g-generated radical-square-zero local algebra: one vertex, g loops, every
        length-2 path is a relation. g = 3 gives hanlab.local_3gen_radsq."""
        arrows = [(i, "v", "v") for i in range(g)]
        rels = [(i, j) for i in range(g) for j in range(g)]
        return MonomialPresentation(["v"], arrows, rels)

    # -- path arithmetic ----------------------------------------------
    def path_src(self, p):
        return self.src[p[0]]

    def path_tgt(self, p):
        return self.tgt[p[-1]]

    def contains_relation(self, path):
        """True if `path` (tuple of arrow ids) contains some relation as a subpath."""
        n = len(path)
        for L in range(n):
            for r in self.relations:
                lr = len(r)
                if L + lr <= n and tuple(path[L:L + lr]) == r:
                    return True
        return False

    def _witness_at_end(self, path):
        """The unique tip that is a suffix of `path`, or None (S is interreduced, so at
        most one tip ends at a given position)."""
        lp = len(path)
        for r in self.relations:
            lr = len(r)
            if lr <= lp and tuple(path[lp - lr:]) == r:
                return r
        return None

    def compose(self, w1, w2):
        """Concatenate paths w1 then w2 (tuples of arrow ids; () = empty/vertex path).
        Returns the reduced path, or None if it does not compose or is 0 in A."""
        if len(w1) == 0:
            cat = tuple(w2)
        elif len(w2) == 0:
            cat = tuple(w1)
        else:
            if self.tgt[w1[-1]] != self.src[w2[0]]:
                return None
            cat = tuple(w1) + tuple(w2)
        if self.contains_relation(cat):
            return None
        return cat

    # -- associated paths ---------------------------------------------
    def associated_paths(self, n, maxlen):
        """AP^n: the degree-n associated paths (n-ambiguities), CS §3 verbatim: each
        next block is the SHORTEST extension making (prev block)+(block) reducible;
        the witness tip ends at the pair's end and may STRADDLE the boundary (a proper
        suffix of the pair — the pair need not itself be a tip). maxlen caps the path
        length explored (an associated path of degree n has length <= n*(maxrel-1)+1;
        pass a generous bound)."""
        if n <= 0:
            return []
        if n == 1:
            return [(a,) for (a, s, t) in self.arrows]
        res = set()

        def rec(blocks, full):
            if len(blocks) == n:
                res.add(tuple(full))
                return
            prev = blocks[-1]
            cur = self.tgt[prev[-1]]

            def ext(uk, lastt):
                cand = tuple(prev) + tuple(uk)
                w = self._witness_at_end(cand)
                if w is not None:
                    # FIRST reducibility: the block boundary is forced here (CS §3 (ii)).
                    if len(w) > len(uk):        # witness straddles => uk irreducible
                        rec(blocks + [tuple(uk)], full + list(uk))
                    return                       # witness inside uk alone: dead branch
                # a valid block uk has len(uk) < len(witness) <= maxrel: bound the search.
                if len(uk) >= self.maxrel:
                    return
                if len(full) + len(uk) > maxlen:
                    return
                for a in self.bysrc.get(lastt, []):
                    ext(uk + [a], self.tgt[a])

            for a in self.bysrc.get(cur, []):
                ext([a], self.tgt[a])

        for (a, s, t) in self.arrows:
            rec([(a,)], [a])
        return sorted(res, key=lambda p: (len(p), p))

    def left_decomposition(self, p, n):
        """Unique CS §3 left block decomposition p = u_0 ... u_{n-1} (n blocks): u_0 =
        first arrow; each next block is the SHORTEST extension making the consecutive
        pair reducible (witness tip ends at the pair's end, straddling the boundary)."""
        if n == 1:
            return [(p[0],)]
        blocks, pos = [(p[0],)], 1
        while len(blocks) < n:
            prev, uk, cut = blocks[-1], [], False
            while pos < len(p):
                uk.append(p[pos])
                pos += 1
                w = self._witness_at_end(tuple(prev) + tuple(uk))
                if w is not None:
                    assert len(w) > len(uk), ("block reducible in left decomposition", p, n)
                    cut = True
                    break
            assert cut, ("no left decomposition for associated path", p, n)
            blocks.append(tuple(uk))
        assert pos == len(p), ("left decomposition does not exhaust the path", p, n)
        return blocks

    def _witness_at_start(self, path):
        """The unique tip that is a prefix of `path`, or None (mirror of _witness_at_end)."""
        lp = len(path)
        for r in self.relations:
            lr = len(r)
            if lr <= lp and tuple(path[:lr]) == r:
                return r
        return None

    def right_decomposition(self, p, n):
        """Unique CS §3 RIGHT block decomposition p = v_{n-1} ... v_0, returned
        left-to-right (n blocks): v_0 = LAST arrow; growing leftwards, each next block
        is the SHORTEST extension making (block)+(prev block) reducible (witness tip
        starts at the pair's start, straddling the boundary). Right ambiguities = left
        ambiguities as sets (CS §3 Prop.), but the BLOCKS differ beyond the quadratic/
        palindromic cases — the odd (2-term) differential needs these for its first term."""
        if n == 1:
            return [(p[-1],)]
        blocks, pos = [(p[-1],)], len(p) - 1        # collected right-to-left
        while len(blocks) < n:
            prev, uk, cut = blocks[-1], [], False
            while pos > 0:
                pos -= 1
                uk.insert(0, p[pos])
                w = self._witness_at_start(tuple(uk) + tuple(prev))
                if w is not None:
                    assert len(w) > len(uk), ("block reducible in right decomposition", p, n)
                    cut = True
                    break
            assert cut, ("no right decomposition for associated path", p, n)
            blocks.append(tuple(uk))
        assert pos == 0, ("right decomposition does not exhaust the path", p, n)
        return blocks[::-1]

    # -- tensored-down term: loops closing an associated path ----------
    def _all_basis_paths(self, maxlen):
        """All nonzero paths of A up to length maxlen, plus the empty path at each
        vertex (vertices encoded as ('v', v), nonempty as ('p', tuple))."""
        out = [("v", v) for v in self.vertices]

        def rec(seq, lastt):
            out.append(("p", tuple(seq)))
            if len(seq) == maxlen:
                return
            for a in self.bysrc.get(lastt, []):
                cand = tuple(seq) + (a,)
                if not self.contains_relation(cand):
                    rec(list(cand), self.tgt[a])

        for (a, s, t) in self.arrows:
            if not self.contains_relation((a,)):
                rec([a], self.tgt[a])
        return out

    def loops(self, o, t, basis_paths):
        """Basis of e_o A e_t = paths from t to o (the loop-space closing an
        associated path with source o, target t). Returns list of path tuples,
        including () for the empty path when o == t."""
        res = []
        for kind, val in basis_paths:
            if kind == "v":
                if val == o and val == t:
                    res.append(())
            else:
                if self.src[val[0]] == t and self.tgt[val[-1]] == o:
                    res.append(val)
        return res


# ----------------------------------------------------------------------
# Bardzell resolution backend
# ----------------------------------------------------------------------
class BardzellResolution(Resolution):
    """Homology-only backend: minimal Bardzell bimodule resolution of a monomial
    algebra, supplied as a MonomialPresentation. Cross-checked exactly against
    BarResolution on the overlap range and run far past the bar-complex depth cap.

    Usage:
        pres = MonomialPresentation.local_radsq(3)
        H.homology_dims(A, N, resolution=BardzellResolution(pres))
    """

    def __init__(self, presentation, maxlen=None):
        self.pres = presentation
        self._maxlen = maxlen
        self._basis_paths_cache = {}
        self._ap_cache = {}

    # -- internal helpers ----------------------------------------------
    def _path_bound(self, n):
        if self._maxlen is not None:
            return self._maxlen
        # an n-associated path has length <= n*(maxrel-1)+1; the loops closing it are
        # nonzero paths, whose length is bounded by maxrel-1 (longer paths hit a
        # relation). Be generous.
        return (n + 2) * max(self.pres.maxrel, 2) + 2

    def _basis_paths(self, n):
        key = self._path_bound(n)
        if key not in self._basis_paths_cache:
            self._basis_paths_cache[key] = self.pres._all_basis_paths(key)
        return self._basis_paths_cache[key]

    def _ap(self, n):
        if n not in self._ap_cache:
            self._ap_cache[n] = self.pres.associated_paths(n, self._path_bound(n))
        return self._ap_cache[n]

    # -- Resolution contract -------------------------------------------
    def term_basis(self, alg, n):
        pres = self.pres
        bp = self._basis_paths(n)
        if n == 0:
            out = []
            for v in pres.vertices:
                for w in pres.loops(v, v, bp):
                    out.append((("v", v), w))
            return out
        out = []
        for p in self._ap(n):
            o = pres.path_src(p)
            t = pres.path_tgt(p)
            for w in pres.loops(o, t, bp):
                out.append((p, w))
        return out

    def differential_matrix(self, alg, n, basis_n, index_nm1):
        pres = self.pres
        rows = len(index_nm1)
        cols = len(basis_n)
        M = np.zeros((rows, cols), dtype=np.int64)

        if n == 1:
            # d_1(x, w) = (t(x); w.x) - (o(x); x.w)
            for c, (x, w) in enumerate(basis_n):
                o = pres.path_src(x)
                t = pres.path_tgt(x)
                lw = pres.compose(w, x)              # w then x : t -> t
                if lw is not None:
                    key = (("v", t), lw)
                    if key in index_nm1:
                        M[index_nm1[key], c] += 1
                lw = pres.compose(x, w)              # x then w : o -> o
                if lw is not None:
                    key = (("v", o), lw)
                    if key in index_nm1:
                        M[index_nm1[key], c] -= 1
            return M

        if n % 2 == 0:
            # BIG map: sum over (n-1)-associated subpaths q of p
            APnm1 = self._ap(n - 1)
            for c, (p, w) in enumerate(basis_n):
                L = len(p)
                for q in APnm1:
                    lq = len(q)
                    for st in range(0, L - lq + 1):
                        if tuple(p[st:st + lq]) == q:
                            pre = tuple(p[:st])
                            suf = tuple(p[st + lq:])
                            lw = pres.compose(suf, w)   # suf . w . pre  (t(q)->o(q))
                            if lw is None:
                                continue
                            lw = pres.compose(lw, pre)
                            if lw is None:
                                continue
                            key = (q, lw)
                            if key in index_nm1:
                                M[index_nm1[key], c] += 1
            return M

        # n odd >= 3: SMALL map
        for c, (p, w) in enumerate(basis_n):
            blocks = pres.left_decomposition(p, n)
            P = tuple(x for b in blocks[1:] for x in b)     # drop first block u_0
            Q = tuple(x for b in blocks[:-1] for x in b)    # drop last block  u_{n-1}
            u0 = blocks[0]
            ulast = blocks[-1]
            lw = pres.compose(w, u0)                         # (P ; w.u_0)
            if lw is not None:
                key = (P, lw)
                if key in index_nm1:
                    M[index_nm1[key], c] += 1
            lw = pres.compose(ulast, w)                      # (Q ; u_{n-1}.w)
            if lw is not None:
                key = (Q, lw)
                if key in index_nm1:
                    M[index_nm1[key], c] -= 1
        return M
