"""The trace submodule tr_{add S}(M) (Plan 47). Self-certifying: iota is mono, its image is
A-stable, every Hom(N,M) factors through iota, and tr is idempotent-monotone. Over QQ AND
GF(2) -- trace_module is pure linear algebra, no char caveat."""
import pytest

from quiverlab import GF, linear_path_algebra
from quiverlab.fields import QQ
from quiverlab.modules import linalg_mod as lm
from quiverlab.modules.morphism import hom_basis
from quiverlab.modules.quasihereditary import trace_module

pytestmark = pytest.mark.oracle_selfcert


def _a3(field=QQ):
    return linear_path_algebra(3, field=field)


def test_trace_of_P2_in_P1_is_the_radical():
    # kA3 (1->2->3): P1 = [1..3], P2 = [2..3]. Hom(P2, P1) = P1 e_2 = e_1 A e_2 = {a} (1-dim),
    # its image is the submodule generated by a = [2..3] = rad P1. So tr_{P2}(P1) = rad P1.
    A = _a3()
    P1, P2 = A.projective(1), A.projective(2)
    T, iota = trace_module([P2], P1)
    assert iota.is_mono()
    assert T.dimension_vector() == P1.radical().dimension_vector()   # {2:1, 3:1}


def test_trace_factors_every_hom():
    A = _a3()
    P1 = A.projective(1)
    sources = [A.projective(2), A.projective(3)]
    T, iota = trace_module(sources, P1)
    # every h: N -> P1 (N in sources) lands inside im(iota): solve iota . x = h columnwise.
    dom = A.domain
    imgcols = [lm.col(iota.matrix, j) for j in range(T.dim)]
    B = lm.cols_to_matrix(imgcols) if imgcols else []
    for N in sources:
        for h in hom_basis(N, P1):
            for j in range(N.dim):
                col = lm.col(h.matrix, j)
                assert lm.solve_columns(B, lm.cols_to_matrix([col]), dom) is not None


def test_trace_is_A_stable_over_GF2():
    # pure linear algebra: no char restriction. tr is a genuine submodule (action-closed).
    A = _a3(GF(2))
    P1 = A.projective(1)
    T, iota = trace_module([A.projective(2)], P1)
    assert T.dim == 2


def test_empty_sources_is_zero_submodule():
    A = _a3()
    P1 = A.projective(1)
    T, iota = trace_module([], P1)
    assert T.dim == 0 and iota.is_mono()


def test_cross_algebra_refused():
    from quiverlab.errors import QuiverlabError
    A, B = _a3(), _a3()
    with pytest.raises(QuiverlabError):
        trace_module([A.projective(2)], B.projective(1))
