"""tau-exceptional sequences (Buan-Marsh) via the Jasso tau-perpendicular reduction
(Plan 65 / R27; Buan-Marsh J. Algebra 585 (2021); Jasso IMRN 2015; Demonet-Iyama-Jasso 2019).

Over a **tau-tilting-finite** ``A = kQ/I`` the *signed* tau-exceptional sequences are built on
the shipped P45 tau-tilting engine:

- a length-1 **signed tau-exceptional object** is either an indecomposable **tau-rigid**
  module ``(M, +)`` or a **shifted projective** ``(P_v[1], -)`` (one per vertex);
- a complete signed tau-exceptional sequence ``(M_1, ..., M_n)`` has, at one end, a signed
  object ``M`` of ``A``, and the remaining ``n-1`` terms form a complete signed
  tau-exceptional sequence of the **reduction algebra** ``C(M)`` -- the Jasso
  tau-perpendicular category ``J(M) ~ mod C(M)``, of rank ``n - |M|``.

The reduction dispatches on the SIGN of the outer object (H2):

- **tau-rigid module ``U``** -> the DIJ idempotent quotient ``C(U) = End(T_U)/<e_U>``
  (``T_U`` a genuine tau-tilting module -- an empty-support exchange-graph vertex -- with
  ``U in add T_U``). We build ``End(T_U)`` in the ``hom_basis`` and quotient by the
  two-sided ideal generated by the summand projector ``e_U`` **at the structure-constant
  level**, THEN present the quotient (``presented_form``). This sidesteps a fragile
  vertex-identification in the presented ``End(T_U)`` (H5): the quotient is intrinsic and
  ``C(S_1) of kA_3`` comes out ``kA_2`` (connected, dim 3), not ``k x k`` (dim 2).
- **shifted projective ``P_v[1]``** -> the support quotient ``C(P_v[1]) = A/<e_v>`` (delete
  vertex ``v``), with ``F`` the tautological restriction ``mod(A/<e_v>) ~ {M in mod A : M_v
  = 0}`` (``Recollement.i_upper_star``).

**Enumeration** is the Buan-Marsh **ordered-support-tau-tilt bijection**:
``#(complete signed tau-exceptional sequences) = n! * #(support tau-tilting pairs)``, with
``#sTt = len(exchange_graph(A).vertices)`` from P45. It is NOT a mutation-BFS (mutation
transitivity is proven only in rank 2, Buan-Hanson-Marsh arXiv:2402.10301). The formula
identity ``signed_count == n! * #sTt`` is a SELF-CERT (tautological); the genuine
cross-check is the **materialisation** of the reduction towers (``want_sequences=True``):
their number equals ``signed_count``, they are pairwise distinct, and each is recognized.

**Honest gates (M1):** the count is trustworthy only from a ``status="complete"`` exchange
graph; ``status in {"budget","error"}`` -> a loud refusal report, never a count off a
non-complete graph. tau-tilting-infinite -> refusal. Char ``<= dim`` over ``GF(p)`` -> the
shipped decompose/is_isomorphic/presented_form caveat raises loudly.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from math import factorial

from quiverlab.errors import QuiverlabError


# --------------------------------------------------------------------------- #
# signed tau-exceptional objects
# --------------------------------------------------------------------------- #
@dataclass
class TauExcObject:
    """A length-1 signed tau-exceptional object: ``sign = +1`` for an indecomposable
    tau-rigid module (``module``), ``sign = -1`` for a shifted projective ``P_vertex[1]``
    (``module = None``, ``vertex`` set)."""
    sign: int
    module: object = None
    vertex: object = None

    def dvt(self):
        """A hashable signature: (sign, dim-vector-tuple) for a module; (sign, ('P', vertex))
        for a shifted projective."""
        if self.sign < 0:
            return (-1, ("P", self.vertex))
        dv = self.module.dimension_vector()
        return (1, tuple(dv[w] for w in sorted(dv)))

    def __repr__(self):
        if self.sign < 0:
            return f"P_{self.vertex}[1]"
        dv = self.module.dimension_vector()
        return "(" + ",".join(str(dv[w]) for w in sorted(dv)) + ")"


@dataclass
class TauReduction:
    """The Jasso tau-perpendicular reduction ``C(U)`` of a signed object ``U`` (Plan 65 /
    R27). ``reduction_algebra`` is a genuine ``kQ'/I'`` Algebra of rank ``n - |U|``;
    ``kind`` is ``"tau_rigid"`` (DIJ ``End(T_U)/<e_U>``) or ``"shifted"`` (``A/<e_v>``);
    ``bongartz`` is the tau-tilting completion ``T_U`` (the pair, tau-rigid case) or ``None``;
    ``u_vertices`` records the killed summand indices / the deleted vertex; ``equivalence``
    is the object-transport ``mod C(U) -> J(U) inverse`` (a callable, shifted case only --
    the cheap restriction; ``None`` for the tau-rigid case, whose deep lift is scope-bounded
    -- see the module docstring)."""
    reduction_algebra: object
    bongartz: object = None
    u_vertices: object = None
    kind: str = "tau_rigid"
    equivalence: object = None


@dataclass
class TauExcReport:
    """The signed tau-exceptional-sequence report of a tau-tilting-finite algebra
    (Plan 65 / R27)."""
    algebra: object
    n: int
    signed_count: int = 0            # = n! * #sTt  (the bijection count; 0 iff not complete)
    stt_count: int = 0               # #support tau-tilting pairs (P45); 0 iff not complete
    sequences: list | None = None    # reduction towers (None if want_sequences=False/capped)
    is_complete: bool = False        # False iff tau-tilting-infinite / non-complete graph
    status: str = "unsupported"      # "complete" | "budget" | "unsupported" | "error"
    note: str = ""


@dataclass
class _TowerEntry:
    """One rung of a materialised reduction tower: a signed object ``obj`` living over the
    algebra ``algebra`` (of rank ``rank``). A complete signed tau-exceptional sequence is
    the tower ``[(A, M_n), (C(M_n), M_{n-1}), ..., (rank-1 algebra, M_1)]``. ``index`` is the
    object's position in its level's enumeration -- it disambiguates NON-isomorphic objects
    with a coinciding dim-vector (e.g. ``P_1``/``P_2`` of ``k(1<->2)/rad^2``, both dim-vector
    ``(1,1)``), which ``dvt`` alone cannot."""
    algebra: object
    obj: TauExcObject
    rank: int
    index: int = -1

    def key(self):
        """A per-rung dedup signature ``(rank, index, obj.dvt())``. Along a tower the tuple
        of rung keys is a UNIQUE path key: a shared prefix => the same reduction algebra =>
        the same enumeration => distinct objects have distinct ``index``."""
        return (self.rank, self.index, self.obj.dvt())


def _require_quiver(A, what):
    if getattr(A, "quiver", None) is None:
        raise QuiverlabError(
            f"{what}: requires a quiver-presented algebra kQ/I (a structure-constant-only "
            "algebra has no vertices to reduce)")


def _rank(A):
    return len(list(A.quiver.vertices))


def _provably_tau_tilting_infinite(A):
    """A CHEAP sufficient certificate of tau-tilting-INfiniteness (never a false positive):
    a **hereditary** connected **non-Dynkin** ``kQ`` is representation-infinite (Gabriel),
    hence tau-tilting-infinite -- refuse instantly, never build the (infinite) exchange
    graph (the 2-Kronecker walk is unbounded). Returns ``False`` (unknown) for every other
    algebra, deferring to the honest exchange-graph budget cap."""
    if getattr(A, "quiver", None) is None:
        return False
    from quiverlab.invariants.dynkin_type import dynkin_type, is_connected
    from quiverlab.invariants.recognizers import is_hereditary
    if is_hereditary(A) and is_connected(A.quiver):
        dt = dynkin_type(A.quiver)
        return not (dt and dt[0] in ("A", "D", "E"))
    return False


# --------------------------------------------------------------------------- #
# the length-1 signed objects
# --------------------------------------------------------------------------- #
def _indec_tau_rigids_from_eg(eg):
    """The indecomposable tau-rigid modules = the union of the exchange-graph pairs'
    summands, deduped by ``is_isomorphic`` within a dim-vector bucket (a distinct object
    with a coinciding dim-vector is kept -- the object count must be exact for the
    materialisation cross-check)."""
    from quiverlab.modules.hom import is_isomorphic
    seen = []                                            # (dvt, module)
    indecs = []
    for rec in eg.vertices:
        for M in rec["pair"].summands:
            dv = M.dimension_vector()
            key = tuple(dv[w] for w in sorted(dv))
            if any(k == key and is_isomorphic(m, M) for k, m in seen):
                continue
            seen.append((key, M))
            indecs.append(M)
    return indecs


def _objects_from_eg(A, eg):
    """The length-1 signed tau-exceptional objects from a complete exchange graph: every
    indecomposable tau-rigid module (sign +1) plus one shifted projective ``P_v[1]`` per
    vertex (sign -1)."""
    objs = [TauExcObject(1, module=M) for M in _indec_tau_rigids_from_eg(eg)]
    for v in A.quiver.vertices:
        objs.append(TauExcObject(-1, vertex=v))
    return objs


def tau_exceptional_objects(A, *, budget=512):
    """The length-1 signed tau-exceptional objects of ``A`` (Plan 65 / R27): every
    indecomposable **tau-rigid** module (sign ``+1``, from the exchange-graph module
    universe) plus one **shifted projective** ``P_v[1]`` per vertex (sign ``-1``). Requires a
    tau-tilting-finite ``A`` for the module part (loud refusal otherwise)."""
    _require_quiver(A, "tau_exceptional_objects")
    if _provably_tau_tilting_infinite(A):
        raise QuiverlabError(
            "tau_exceptional_objects: a hereditary connected non-Dynkin algebra is "
            "representation-infinite (Gabriel), hence tau-tilting-infinite; the tau-rigid "
            "module universe is infinite")
    from quiverlab.tautilting.mutation import exchange_graph
    eg = exchange_graph(A, budget_pairs=budget)
    if eg.status != "complete":
        raise QuiverlabError(
            "tau_exceptional_objects: the exchange graph is not complete "
            f"(status={eg.status!r}); the tau-rigid module universe is unavailable "
            "(tau-tilting-infinite or a P45 mutation failure)")
    return _objects_from_eg(A, eg)


# --------------------------------------------------------------------------- #
# Task A1: the Jasso tau-perpendicular reduction C(U)
# --------------------------------------------------------------------------- #
def _quotient_by_idempotent_sc(B0, e):
    """The quotient ``B0 / <e>`` of a structure-constant algebra by the two-sided ideal
    generated by the idempotent (coordinate vector) ``e``, returned as a NEW
    structure-constant :class:`Algebra`. ``<e> = B0 . e . B0`` (``B0`` has 1); the quotient
    basis is a complement of ``<e>``, structure constants induced by projection along
    ``<e>``. Exact, no floats."""
    from quiverlab.core.algebra import Algebra
    from quiverlab.fields.linalg import solve
    from quiverlab.modules import linalg_mod as lm
    dom = B0.domain
    r = B0.dim
    left = [B0.multiply(B0._basis_vec(a), e) for a in range(r)]        # B0 . e
    prods = [B0.multiply(l, B0._basis_vec(c)) for l in left for c in range(r)]   # B0.e.B0
    Jidx = lm.independent_modulo(prods, [], dom)
    Jbasis = [prods[i] for i in Jidx]
    std = [B0._basis_vec(i) for i in range(r)]
    comp_idx = lm.independent_modulo(std, Jbasis, dom)                 # complement of <e>
    comp = [std[i] for i in comp_idx]
    c = len(comp)
    basis_mat = lm.cols_to_matrix(comp + Jbasis)                       # square r x r, invertible

    def proj(x):
        sol = solve(basis_mat, list(x), dom)
        if sol is None:
            raise QuiverlabError(
                "tau_perpendicular_reduction: quotient projection failed -- the "
                "complement/ideal split is not a basis (bug)")
        return list(sol[:c])

    Tq = [[proj(B0.multiply(comp[i], comp[j])) for j in range(c)] for i in range(c)]
    unitq = proj(list(B0.unit))
    return Algebra.from_structure_constants(Tq, unitq, field=dom, check=True)


def _reduction_tau_rigid(A, Umod, eg):
    """``C(U) = End(T_U)/<e_U>`` for a tau-rigid indecomposable ``Umod`` (the DIJ idempotent
    quotient). ``T_U`` = an empty-support exchange-graph vertex (a genuine tau-tilting
    module) containing ``Umod``; ``e_U`` = its summand projector. Returns
    ``(C, pair, u_summand_indices)``."""
    from quiverlab.core.algebra import Algebra
    from quiverlab.core.basic import presented_form
    from quiverlab.fields.linalg import solve
    from quiverlab.modules.endomorphism import _structure_constants, _vec
    from quiverlab.modules.hom import is_isomorphic
    from quiverlab.modules.morphism import direct_sum

    def _iso(M):
        return (M.dim == Umod.dim
                and M.dimension_vector() == Umod.dimension_vector()
                and is_isomorphic(M, Umod))

    pair = None
    for rec in eg.vertices:
        if rec["support"]:                              # only genuine tau-tilting modules
            continue
        if any(_iso(M) for M in rec["pair"].summands):
            pair = rec["pair"]
            break
    if pair is None:
        raise QuiverlabError(
            "tau_perpendicular_reduction: no tau-tilting completion of U found among the "
            "empty-support exchange-graph vertices (U not tau-rigid, or tau-tilting-infinite)")
    summands = list(pair.summands)
    D, incls, projs = direct_sum(*summands)
    dom = D.domain
    Tsc, unit, _basis, Bmat = _structure_constants(D)
    B0 = Algebra.from_structure_constants(Tsc, list(unit), field=dom, check=True)
    r = B0.dim
    eU = [dom.zero()] * r
    uverts = []
    for i, Mi in enumerate(summands):
        if _iso(Mi):
            proj_endo = projs[i].then(incls[i])         # incl_i o proj_i : D -> D idempotent
            coords = solve(Bmat, _vec(proj_endo.matrix, D.dim), dom)
            if coords is None:
                raise QuiverlabError(
                    "tau_perpendicular_reduction: summand projector left the hom basis (bug)")
            eU = [dom.add(eU[t], coords[t]) for t in range(r)]
            uverts.append(i)
    C0 = _quotient_by_idempotent_sc(B0, eU)
    C = presented_form(C0)
    return C, pair, uverts


def tau_perpendicular_reduction(A, U, *, budget=512, _eg=None):
    """The Jasso tau-perpendicular reduction ``C(U)`` of a signed tau-exceptional object
    ``U`` (Plan 65 / R27), dispatching on the sign of ``U`` (H2):

    - ``U`` a **tau-rigid module** (a :class:`~quiverlab.modules.module.Module`, or a
      positive :class:`TauExcObject`): the DIJ quotient ``C(U) = End(T_U)/<e_U>`` (rank
      ``n - |U|``);
    - ``U`` a **shifted projective** ``P_v[1]`` (a negative :class:`TauExcObject`): the
      support quotient ``C(P_v[1]) = A/<e_v>`` (rank ``n - 1``), with the tautological
      restriction transport.

    Returns a :class:`TauReduction`. Self-certifies ``rk C(U) = n - |U|`` and (tau-rigid
    case) is discriminated by the ``C(S_1 of kA_3) = kA_2`` iso pin (H5)."""
    _require_quiver(A, "tau_perpendicular_reduction")
    if isinstance(U, TauExcObject) and U.sign < 0:      # shifted projective P_v[1]
        from quiverlab.modules.recollement import Recollement
        v = U.vertex
        recoll = Recollement(A, [v])
        return TauReduction(
            reduction_algebra=recoll.quotient, bongartz=None, u_vertices=[v],
            kind="shifted", equivalence=(lambda M, _r=recoll: _r.i_upper_star(M)))
    Umod = U.module if isinstance(U, TauExcObject) else U
    if Umod is None:
        raise QuiverlabError(
            "tau_perpendicular_reduction: a positive TauExcObject with no module")
    from quiverlab.tautilting.mutation import exchange_graph
    eg = _eg if _eg is not None else exchange_graph(A, budget_pairs=max(budget, 512))
    if eg.status != "complete":
        raise QuiverlabError(
            "tau_perpendicular_reduction: the exchange graph is not complete "
            f"(status={eg.status!r}); U cannot be tau-Bongartz-completed")
    C, pair, uverts = _reduction_tau_rigid(A, Umod, eg)
    return TauReduction(reduction_algebra=C, bongartz=pair, u_vertices=uverts,
                        kind="tau_rigid", equivalence=None)


# --------------------------------------------------------------------------- #
# Task A2: the recognizer
# --------------------------------------------------------------------------- #
def _is_signed_object(A, obj):
    """True iff ``obj`` (a :class:`TauExcObject`, over algebra ``A``) is a genuine length-1
    signed tau-exceptional object of ``A``."""
    from quiverlab.modules.decompose import is_indecomposable
    from quiverlab.tautilting.rigid import is_tau_rigid
    if not isinstance(obj, TauExcObject):
        return False
    if obj.sign < 0:
        return obj.vertex in set(A.quiver.vertices)
    M = obj.module
    if M is None or getattr(M, "algebra", None) is not A:
        return False
    return is_tau_rigid(M) and is_indecomposable(M)


def _entry_module(x):
    """The genuine module of an ambient sequence entry (a :class:`Module` or a positive
    :class:`TauExcObject`), else ``None`` (a shifted object)."""
    if isinstance(x, TauExcObject):
        return x.module if x.sign > 0 else None
    return x


def _entry_shift_vertex(x):
    """The shifted-projective vertex of an ambient sequence entry, else ``None``."""
    if isinstance(x, TauExcObject) and x.sign < 0:
        return x.vertex
    return None


def _verify_tower(A, seq):
    """A materialised tower ``[(A, M_n), (C_1, M_{n-1}), ...]`` is genuine iff every rung's
    object is a signed tau-exceptional object of its algebra, the ranks descend
    ``n, n-1, ..., 1``, and the length is ``n = rk A``."""
    n = _rank(A)
    if len(seq) != n:
        return False
    if seq and seq[0].algebra is not A:
        return False
    for i, entry in enumerate(seq):
        if entry.rank != n - i:
            return False
        if _rank(entry.algebra) != n - i:
            return False
        if not _is_signed_object(entry.algebra, entry.obj):
            return False
    return True


def is_tau_exceptional_sequence(A, seq):
    """True iff ``seq`` is a complete-or-partial signed tau-exceptional sequence of ``A``
    (Plan 65 / R27; the ``(inner, ..., outer)`` convention -- the outer term is the
    reduced-away end ``seq[-1]``).

    Two input forms are accepted:

    - a **reduction tower** (a list of :class:`_TowerEntry`, as produced by
      :func:`tau_exceptional_sequences`): verified rung-by-rung;
    - an **ambient sequence** (a list of :class:`Module` / :class:`TauExcObject`): recognized
      recursively -- the outer signed object reduces, the remaining terms are transported
      into ``C(outer)`` and recognized there. Over a hereditary ``A`` an all-module sequence
      is recognized by the classical criterion (the Buan-Marsh coincidence, tau-exc =
      classical exc for hereditary)."""
    _require_quiver(A, "is_tau_exceptional_sequence")
    seq = list(seq)
    if not seq:
        return True
    if all(isinstance(e, _TowerEntry) for e in seq):
        return _verify_tower(A, seq)
    return _recognize_ambient(A, seq)


def _recognize_ambient(A, seq):
    from quiverlab.invariants.recognizers import is_hereditary
    # hereditary + all-module: tau-exceptional == classical exceptional (Buan-Marsh)
    mods = [_entry_module(x) for x in seq]
    if all(m is not None for m in mods) and is_hereditary(A):
        from quiverlab.modules.exceptional import is_exceptional_sequence
        return is_exceptional_sequence(A, mods)
    # general: validate the outer object, reduce, transport the inner terms, recurse
    outer = seq[-1]
    if not _as_signed_and_valid(A, outer):
        return False
    if len(seq) == 1:
        return True
    v = _entry_shift_vertex(outer)
    if v is None:
        # tau-rigid outer over a non-hereditary / mixed ambient sequence: the deep
        # object-lift F^{-1} is scope-bounded (honest -- see the module docstring). The
        # hereditary all-module case is handled above; the count oracle carries completeness.
        raise QuiverlabError(
            "is_tau_exceptional_sequence: an ambient sequence with a tau-rigid OUTER term "
            "over a non-hereditary algebra needs the deep tau-perpendicular object-lift "
            "F^{-1}, which is scope-bounded (Plan 65 honest scope); pass the reduction "
            "tower form, or use the count oracle (n! * #sTt)")
    red = tau_perpendicular_reduction(A, _as_shift_object(A, outer))
    C, transport = red.reduction_algebra, red.equivalence
    inner = []
    for x in seq[:-1]:
        m = _entry_module(x)
        if m is None:
            inner.append(x)                             # a shifted inner stays shifted
            continue
        if m.dimension_vector().get(v, 0) != 0:
            return False                                # not supported off v: not in J(P_v[1])
        inner.append(transport(m))
    return is_tau_exceptional_sequence(C, inner)


def _as_signed_and_valid(A, x):
    """True iff the ambient entry ``x`` is a genuine length-1 signed tau-exceptional object
    of ``A`` (a tau-rigid indecomposable module, or a shifted projective)."""
    from quiverlab.modules.decompose import is_indecomposable
    from quiverlab.tautilting.rigid import is_tau_rigid
    v = _entry_shift_vertex(x)
    if v is not None:
        return v in set(A.quiver.vertices)
    m = _entry_module(x)
    if m is None or getattr(m, "algebra", None) is not A:
        return False
    return is_tau_rigid(m) and is_indecomposable(m)


def _as_shift_object(A, x):
    """Coerce an ambient shifted entry to a negative :class:`TauExcObject` for the reduction
    sign-dispatch."""
    if isinstance(x, TauExcObject):
        return x
    return TauExcObject(-1, vertex=_entry_shift_vertex(x))


# --------------------------------------------------------------------------- #
# Task A3: enumeration via the ordered-sTt bijection + materialisation
# --------------------------------------------------------------------------- #
def _enumerate_towers(A, eg):
    """The materialised complete signed tau-exceptional sequences of ``A`` as reduction
    towers (Task A3 -- the H1 cross-check). Realises the Buan-Marsh recursion: pick an outer
    signed object ``M``, then a complete tower of ``C(M)``. ``eg`` is the (complete)
    exchange graph of ``A``."""
    n = _rank(A)
    objs = _objects_from_eg(A, eg)
    towers = []
    for i, M in enumerate(objs):
        entry = _TowerEntry(A, M, n, i)
        if n == 1:
            towers.append([entry])
            continue
        C = tau_perpendicular_reduction(A, M, _eg=eg).reduction_algebra
        from quiverlab.tautilting.mutation import exchange_graph
        egC = exchange_graph(C, budget_pairs=max(512, len(eg.vertices)))
        if egC.status != "complete":
            raise QuiverlabError(
                "tau_exceptional_sequences: a reduction algebra C(U) was not "
                f"tau-tilting-finite (status={egC.status!r}) -- unexpected (report it)")
        for sub in _enumerate_towers(C, egC):
            towers.append([entry] + sub)
    return towers


def tau_exceptional_sequences(A, *, budget=4096, want_sequences=True):
    """The complete signed tau-exceptional sequences of a **tau-tilting-finite** ``A``
    (Plan 65 / R27). The count is the ordered-support-tau-tilt bijection
    ``signed_count = n! * #sTt`` with ``#sTt = len(exchange_graph(A).vertices)`` -- computed
    WITHOUT enumerating, so it is exact even when materialisation is budget-capped.

    ``want_sequences=True`` also MATERIALISES the reduction towers (the H1 cross-check:
    ``len(sequences) == signed_count``, pairwise distinct, each recognized), capped at
    ``budget`` towers (``signed_count`` stays exact via the formula). Returns a
    :class:`TauExcReport`.

    Gate (M1): only a ``status="complete"`` exchange graph yields a count; ``status in
    {"budget","error"}`` -> an honest refusal report, NEVER a count off a non-complete graph."""
    _require_quiver(A, "tau_exceptional_sequences")
    from quiverlab.tautilting.mutation import exchange_graph
    n = _rank(A)
    if _provably_tau_tilting_infinite(A):
        return TauExcReport(
            A, n, 0, 0, None, False, "budget",
            "hereditary connected non-Dynkin => representation-infinite (Gabriel) => "
            "tau-tilting-infinite; the signed tau-exceptional count is infinite (no count "
            "derived)")
    eg = exchange_graph(A, budget_pairs=max(budget, 512))
    if eg.status != "complete":
        note = ("the exchange graph is not complete "
                f"(status={eg.status!r}); tau-tilting-infinite or a P45 mutation failure -- "
                "no signed tau-exceptional count is derived from a non-complete graph (M1)")
        status = eg.status if eg.status in ("budget", "error") else "unsupported"
        return TauExcReport(A, n, 0, 0, None, False, status, note)
    stt = len(eg.vertices)
    signed = factorial(n) * stt
    if not want_sequences:
        return TauExcReport(A, n, signed, stt, None, True, "complete", "")
    if signed > budget:
        return TauExcReport(
            A, n, signed, stt, None, True, "complete",
            f"materialisation capped: signed_count={signed} > budget={budget}; the count is "
            "exact via the bijection formula, sequences not materialised")
    towers = _enumerate_towers(A, eg)
    note = ""
    if len(towers) != signed:                           # a genuine reduction bug -> loud note
        note = (f"materialised {len(towers)} towers != signed_count {signed} -- a bug in the "
                "tau-perpendicular reduction or object enumeration (report it)")
    return TauExcReport(A, n, signed, stt, towers, True, "complete", note)


# --------------------------------------------------------------------------- #
# the algebra-only GUI/webapp/hpc block builder (both halves; Plan 65 Task G1)
# --------------------------------------------------------------------------- #
_EXC_REFERENCES = ["buan_marsh_tau_exceptional", "crawley_boevey_exceptional",
                   "ringel_braid", "jasso_reduction", "obaid_dynkin_count",
                   "air_tau_tilting", "assem_book"]


def exceptional_sequences_block(A, budget=100_000):
    """The shared ``exceptional_sequences`` compute block (Plan 65 Task G1): the CLASSICAL
    hereditary surface (counts + braid-orbit transitivity + Dynkin closed form, if
    hereditary) AND the tau-exceptional surface (the signed count ``n!*#sTt``, if
    tau-tilting-finite), each honest about applicability. Sequences themselves are NOT
    shipped (they explode -- ``D_4`` has 162 classical / 1200 signed); the block reports
    counts + status. Presentation-less -> a typed error dict, never a 500.

    Shared by ``hpc/spec.py`` and ``docs/gui/runner.py`` so the blocks are byte-identical."""
    if getattr(A, "quiver", None) is None:
        return {"error": ("exceptional sequences require a quiver-presented algebra kQ/I "
                          "(a structure-constant-only algebra has no exceptional-sequence "
                          "surface)"),
                "references": list(_EXC_REFERENCES)}
    from quiverlab.invariants.dynkin_type import dynkin_type
    from quiverlab.invariants.recognizers import is_hereditary
    n = _rank(A)
    dt = dynkin_type(A.quiver)
    dtype_str = f"{dt[0]}_{dt[1]}" if (dt and dt[0] in ("A", "D", "E")) else None
    hereditary = bool(is_hereditary(A))
    notes = []

    classical = None
    if hereditary:
        rep = A.exceptional_sequences(budget=budget)
        classical = {"count": rep.count, "closed_form_count": rep.closed_form_count,
                     "transitive": rep.transitive, "complete": rep.is_complete,
                     "status": rep.status}
        if rep.note:
            notes.append(rep.note)
    else:
        notes.append("not hereditary: the classical (braid-orbit) surface does not apply")

    trep = A.tau_exceptional_sequences(budget=max(budget, 512), want_sequences=False)
    tau = None
    if trep.is_complete:
        tau = {"signed_count": trep.signed_count, "stt_count": trep.stt_count,
               "complete": trep.is_complete, "status": trep.status}
    else:
        notes.append("tau-exceptional: " + (trep.note or "not tau-tilting-finite"))

    return {"kind": "exceptional_sequences", "n": n,
            "hereditary": hereditary, "dynkin_type": dtype_str,
            "classical": classical, "tau": tau,
            "note": ("; ".join(notes) if notes else None),
            "references": list(_EXC_REFERENCES)}
