"""King theta-(semi)stability + the exact-rational wall-and-chamber fan (Plan 45 / C4,
King 1994; Bridgeland/Brustle-Smith-Treffinger g-fan). A module M is theta-semistable iff
``theta . dim M = 0`` and ``theta . dim N <= 0`` for every submodule N (stable = strict for
0 != N < M). The wall-and-chamber fan: each support tau-tilting pair is a maximal CHAMBER
(the nonneg span of its g-vectors); each exchange edge is a WALL lying in the hyperplane
``{theta : theta . dim B = 0}``, B the mutation brick label -- so the wall NORMAL IS the
brick dim-vector (King). Every payload is EXACT rational (``fractions.Fraction``); the n=2
tiling is checked by exact 2D orientation predicates (no atan2), and n=3 projects by
L1-normalisation to the octahedron (the antipodal (0,A) cone projects off any single affine
plane; L1 keeps the whole fan). Float-free."""
from __future__ import annotations

from fractions import Fraction

from quiverlab.errors import QuiverlabError
from quiverlab.modules import linalg_mod as lm


# --------------------------------------------------------------------------- #
# submodule enumeration (small modules; loud cap otherwise)
# --------------------------------------------------------------------------- #
def _rref_key(cols, nrows, dom):
    """A canonical key (row-reduced echelon, as a tuple of coefficient tuples) for the
    subspace spanned by ``cols`` (each a length-``nrows`` vector)."""
    rows = [list(c) for c in cols]                    # treat vectors as rows to reduce
    rows = [r[:] for r in rows]
    pivots = []
    pr = 0
    ncols = nrows
    for cidx in range(ncols):
        piv = None
        for r in range(pr, len(rows)):
            if not dom.is_zero(rows[r][cidx]):
                piv = r
                break
        if piv is None:
            continue
        rows[pr], rows[piv] = rows[piv], rows[pr]
        inv = dom.inv(rows[pr][cidx])
        rows[pr] = [dom.mul(inv, x) for x in rows[pr]]
        for r in range(len(rows)):
            if r != pr and not dom.is_zero(rows[r][cidx]):
                f = rows[r][cidx]
                rows[r] = [dom.sub(rows[r][k], dom.mul(f, rows[pr][k]))
                           for k in range(ncols)]
        pivots.append(cidx)
        pr += 1
        if pr == len(rows):
            break
    basis = tuple(tuple(rows[r]) for r in range(pr))
    return basis


def _closure_cols(M, seed_cols, dom):
    """The smallest A-submodule of ``M`` containing ``seed_cols``: close under every
    generator action, keeping an independent column basis."""
    labels = [f"e_{v}" for v in M.algebra.quiver.vertices] + list(M.algebra.quiver.arrows)
    basis = []
    for c in seed_cols:
        idx = lm.independent_modulo([c], [list(x) for x in basis], dom)
        if idx:
            basis.append(list(c))
    queue = list(basis)
    while queue:
        w = queue.pop()
        for b in labels:
            img = lm.matvec(M.action[b], w, dom)
            idx = lm.independent_modulo([img], [list(x) for x in basis], dom)
            if idx:
                basis.append(list(img))
                queue.append(list(img))
    return basis


def _dimvec_of_cols(M, cols, dom):
    """The dimension vector of the submodule spanned by ``cols`` (rank of each vertex
    projection restricted to the span)."""
    out = {}
    if not cols:
        return {v: 0 for v in M.algebra.quiver.vertices}
    B = lm.cols_to_matrix(cols)
    for v in M.algebra.quiver.vertices:
        Pv = M.vertex_projection(v)
        proj = lm.matmul(Pv, B, dom)
        out[v] = lm.mat_rank(proj, dom)
    return out


def _submodule_dimvecs(M, budget=4096):
    """The set of dimension vectors of A-submodules of ``M`` (as vertex-key tuples).
    BFS over submodules generated by basis vectors + closure; deduped by RREF key.
    Sufficient and exact for the small modules in the fan; raises loudly past ``budget``."""
    dom = M.domain
    verts = list(M.algebra.quiver.vertices)
    ident = lm.identity(M.dim, dom)
    seen = {}
    empty_key = _rref_key([], M.dim, dom)
    frontier = [[]]
    seen[empty_key] = {v: 0 for v in verts}
    while frontier:
        cols = frontier.pop()
        if len(seen) > budget:
            raise QuiverlabError(
                f"submodule enumeration exceeded budget {budget} for {M.name} "
                f"(dim {M.dim})", hint="King stability on a large module -- raise budget")
        for i in range(M.dim):
            ei = lm.col(ident, i)
            newcols = _closure_cols(M, [list(c) for c in cols] + [ei], dom)
            key = _rref_key(newcols, M.dim, dom)
            if key not in seen:
                seen[key] = _dimvec_of_cols(M, newcols, dom)
                frontier.append(newcols)
    return {tuple(dv[v] for v in verts) for dv in seen.values()}


# --------------------------------------------------------------------------- #
# King theta-(semi)stability
# --------------------------------------------------------------------------- #
def _theta_dot(theta, dimtuple):
    return sum((theta[i] * dimtuple[i] for i in range(len(dimtuple))), Fraction(0))


def is_theta_semistable(M, theta):
    """King 1994: ``M`` is theta-semistable iff ``theta . dim M = 0`` and
    ``theta . dim N <= 0`` for every submodule ``N <= M``. ``theta`` is an exact-rational
    n-vector (list of ``Fraction``/int, vertex order)."""
    verts = list(M.algebra.quiver.vertices)
    theta = [Fraction(t) for t in theta]
    dv = M.dimension_vector()
    if _theta_dot(theta, tuple(dv[v] for v in verts)) != 0:
        return False
    for d in _submodule_dimvecs(M):
        if _theta_dot(theta, d) > 0:
            return False
    return True


def is_theta_stable(M, theta):
    """The strict King condition: ``theta . dim M = 0`` and ``theta . dim N < 0`` for every
    proper nonzero submodule ``0 != N < M``."""
    verts = list(M.algebra.quiver.vertices)
    theta = [Fraction(t) for t in theta]
    dv = M.dimension_vector()
    full = tuple(dv[v] for v in verts)
    if _theta_dot(theta, full) != 0:
        return False
    zero = tuple(0 for _ in verts)
    for d in _submodule_dimvecs(M):
        if d == zero or d == full:
            continue
        if _theta_dot(theta, d) >= 0:
            return False
    return True


# --------------------------------------------------------------------------- #
# exact integer determinant (unimodularity certificate)
# --------------------------------------------------------------------------- #
def _det(mat):
    """Exact integer determinant by fraction-free Gaussian elimination (Bareiss); the
    unimodularity check the fan records per chamber (det +-1)."""
    n = len(mat)
    if n == 0:
        return 1
    M = [[int(x) for x in row] for row in mat]
    sign = 1
    prev = 1
    for k in range(n - 1):
        if M[k][k] == 0:
            swap = next((r for r in range(k + 1, n) if M[r][k] != 0), None)
            if swap is None:
                return 0
            M[k], M[swap] = M[swap], M[k]
            sign = -sign
        for i in range(k + 1, n):
            for j in range(k + 1, n):
                M[i][j] = (M[i][j] * M[k][k] - M[i][k] * M[k][j]) // prev
        prev = M[k][k]
    return sign * M[n - 1][n - 1]


# --------------------------------------------------------------------------- #
# the wall-and-chamber fan
# --------------------------------------------------------------------------- #
def _l1_project(vec):
    """L1-normalise an integer ray to the octahedron ``|x|+|y|+|z| = 1`` (exact
    fractions) and its 2D net position (upper hemisphere -> inner diamond, lower -> the
    four outer corners; a valid exact-rational unfolding of the octahedron)."""
    s = sum(abs(x) for x in vec)
    if s == 0:
        return None, None, None
    p = [Fraction(x, s) for x in vec]
    face = tuple(1 if x > 0 else (-1 if x < 0 else 0) for x in vec)
    x, y, z = p
    if z >= 0:
        net = [x, y]
    else:
        sx = 1 if x > 0 else -1
        sy = 1 if y > 0 else -1
        net = [sx * (abs(x) + abs(z)), sy * (abs(y) + abs(z))]
    return [str(c) for c in p], list(face), [str(c) for c in net]


def wall_and_chamber_fan(A, budget=512):
    """The EXACT-rational wall-and-chamber fan payload for the GUI (drawn for n = 2, 3):
    chambers (one per pair, g-vector rays), walls (one per exchange edge, normal = the
    brick dim-vector). n=3 rays carry an L1/octahedron projection. Honest complete-iff
    contract (``status`` mirrors the exchange graph)."""
    from quiverlab.tautilting.mutation import exchange_graph
    verts = list(A.quiver.vertices)
    n = len(verts)
    eg = exchange_graph(A, budget_pairs=budget)
    out = {"n": n, "vertices": list(verts),
           "complete": eg.is_complete,
           "status": eg.status}
    if not eg.is_complete:
        out["chambers"] = []
        out["walls"] = []
        return out
    chambers = []
    for i, rec in enumerate(eg.vertices):
        G = rec["g_matrix"]
        rays = [[G[r][c] for r in range(n)] for c in range(n)]     # columns = g-vectors
        ch = {"pair_id": i, "g_matrix": G,
              "rays": [[str(Fraction(x)) for x in ray] for ray in rays],
              "is_initial": rec["is_initial"]}
        if n == 3:
            proj = [_l1_project(ray) for ray in rays]
            ch["rays_l1"] = [p[0] for p in proj]
            ch["faces"] = [p[1] for p in proj]
            ch["net2d"] = [p[2] for p in proj]
        chambers.append(ch)
    walls = []
    for (i, j), data in eg.arrows.items():
        bd = data["brick"]                            # brick dim-vector = wall NORMAL (King)
        pi = eg.vertices[i]["pair"]
        pj = eg.vertices[j]["pair"]
        shared = [list(c) for c in sorted(pi.g_key() & pj.g_key())]   # g-vectors IN the wall
        walls.append({"between": [i, j], "brick_dimvec": bd,
                      "normal": shared[0] if shared else None,        # a facet vector
                      "facet": shared})                # brick_dimvec . (each facet vec) = 0
    out["chambers"] = chambers
    out["walls"] = walls
    if n == 3:
        out["projection"] = "L1"
    return out
