"""CC: 'the complex numbers', exactly (spec §4.2). Entries must be exact
algebraic expressions; the actual computation domain is the exact subfield of C
they generate (sympy algebraic field). Dimensions computed there provably equal
the C answers by flat base change."""
from fractions import Fraction

import sympy
from sympy.polys.constructor import construct_domain

from quiverlab.errors import ExactnessError, FieldError
from quiverlab.fields.domain import Domain, reject_inexact

_FLOAT_HINT = "quiverlab is exact-only: write '1/2', 'sqrt(2)', 'i', E(3), never 0.5"


def E(n: int):
    """Primitive n-th root of unity exp(2*pi*i/n), exact (GAP's E(n) convention)."""
    if not (isinstance(n, int) and not isinstance(n, bool) and n >= 1):
        raise FieldError(f"E({n!r}): n must be a positive integer", hint="e.g. E(3), E(8)")
    return sympy.exp(2 * sympy.pi * sympy.I / n)


class SympyExactDomain(Domain):
    """Wraps a sympy field domain (QQ or QQ<alpha>) behind the quiverlab Domain protocol."""

    characteristic = 0

    def __init__(self, sdom):
        self.sdom = sdom
        self.name = f"CC (computing exactly in {sdom})"

    def coerce(self, x):
        expr = CC.parse_entry(x)
        try:
            return self.sdom.from_sympy(expr)
        except Exception as exc:
            raise FieldError(
                f"{expr} does not lie in the exact field {self.sdom} generated by this "
                f"algebra's entries",
                hint="include this number among the algebra's entries at construction",
            ) from exc

    def zero(self):
        return self.sdom.zero

    def one(self):
        return self.sdom.one

    def add(self, a, b):
        return a + b

    def neg(self, a):
        return -a

    def mul(self, a, b):
        return a * b

    def inv(self, a):
        if self.is_zero(a):
            raise ZeroDivisionError("0 has no inverse")
        return self.sdom.exquo(self.sdom.one, a)

    def is_zero(self, a):
        return a == self.sdom.zero

    def to_str(self, a):
        return str(self.sdom.to_sympy(a))


class ComplexField:
    """Field spec for 'the complex numbers'. Not itself a Domain: it inspects all
    entries first, then hands back the exact working Domain (make_domain)."""

    name = "CC"
    characteristic = 0

    def parse_entry(self, x):
        if isinstance(x, sympy.Expr):
            expr = x
        else:
            reject_inexact(x)
            if isinstance(x, int):
                expr = sympy.Integer(x)
            elif isinstance(x, Fraction):
                expr = sympy.Rational(x.numerator, x.denominator)
            elif isinstance(x, str):
                try:
                    expr = sympy.sympify(
                        x, locals={"i": sympy.I, "E": E}, rational=False, evaluate=True
                    )
                except (sympy.SympifyError, TypeError, SyntaxError) as exc:
                    raise FieldError(f"cannot read {x!r} as an exact complex number",
                                     hint="examples: '1/3', 'i', 'sqrt(2)', 'E(3)'") from exc
            else:
                raise FieldError(f"cannot read {type(x).__name__} {x!r} as an exact scalar",
                                 hint=_FLOAT_HINT)
        if not isinstance(expr, sympy.Basic):
            raise FieldError(f"cannot read {x!r} as an exact complex number",
                             hint="examples: '1/3', 'i', 'sqrt(2)', 'E(3)'")
        if expr.atoms(sympy.Float):
            raise ExactnessError(f"{expr} contains a floating-point number", hint=_FLOAT_HINT)
        if not expr.is_number:
            raise FieldError(f"{expr} is not a number", hint="entries must be exact scalars")
        return expr

    def make_domain(self, entries):
        exprs = [self.parse_entry(e) for e in entries]
        try:
            sdom, _ = construct_domain(exprs or [sympy.Integer(0)], field=True, extension=True)
        except Exception as exc:
            raise FieldError(
                "sympy cannot place these entries in an exact algebraic extension of QQ "
                "(spec §4.2: transcendental or unsupported entries fail loudly)",
                hint="stick to rationals, i, radicals and roots of unity E(n)",
            ) from exc
        if not (sdom.is_Field and getattr(sdom, "is_Numerical", False) and sdom.is_Exact):
            raise FieldError(
                f"entries generate {sdom}, not an exact numerical field; genuinely "
                "transcendental entries are out of scope for v1 (spec §4.2)",
                hint="stick to rationals, i, radicals and roots of unity E(n)",
            )
        return SympyExactDomain(sdom)


CC = ComplexField()
