"""The "extension by arrows and relations" input model (CLMS Def. 5.1/5.2) plus the
relative-path combinatorics for the Han bounded-extension recognizer (Plan 73, R7).

Cibils-Lanzilotta-Marcos-Solotar, ``2101.02597`` (J. Algebra 2022). Given a
finite-dimensional ``A = kQ_A/I_A`` and a subset ``F`` of ``(Q_A)_1`` of arrows
designated as **new**, the subalgebra ``B <= A`` generated by the **kept** arrows
``(Q_A)_1 \\ F`` (and the vertices) is an "extension by arrows and relations":
``B = kQ_B/I_B`` with ``Q_B = (Q_0, (Q_A)_1 \\ F)`` and ``I_B = ker(pi: kQ_B -> A)``.
The ``B``-bimodule ``A/B`` is spanned by the **relative paths** -- the ``A``-basis
paths of positive ``F``-length (>= 1 new arrow, CLMS Def. 5.9-5.10).

Composition is left-to-right (quiverlab convention); the CLMS paper composes
right-to-left, so every transcribed path is translated.

**Shared substrate (P72 seam).** P72 (``hochschild/arrow_removal.py``) ships the
inert-arrow reductions ``inert_arrows`` / ``remove_arrows`` / ``add_arrows``.
``remove_arrows`` is the **inert special case** (``I_B = I_A`` verbatim);
``arrow_removal_subalgebra`` here is the general constructor (arbitrary ``F``,
induced ``I_B = ker pi`` -- an ``F``-relation can collapse ``F``-free paths, so the
ideal is NOT "drop the ``F``-relations"). P72 is consumed, not re-implemented: the
cross-consistency test ``remove_arrows == arrow_removal_subalgebra`` on an inert
``F`` is the adjudicated seam gate (``tests/families/test_extension.py``). The
honest constructor drives the shipped ``families/_present.py::present_from_pi``
(Plan 44) to extract ``ker pi`` and certify ``dim B``.
"""
import itertools
from dataclasses import dataclass, field as _field

from quiverlab.errors import QuiverlabError
from quiverlab.families._present import present_from_pi
from quiverlab.fields.linalg import rank, rref

_EXT_CITATIONS = ("clms_bounded_extensions", "han_conjecture")

#: guard on the number of columns ``|R|^m`` of a direct tensor-power computation
#: (the relative-path tensor blows up combinatorially; past this the direct route
#: is refused as infeasible and the recognizer falls to the capped semi-decision).
_MAX_TENSOR_CELLS = 20000


# --------------------------------------------------------------------------- #
# relative-path token combinatorics (guards the 'al' vs 'a' whole-token trap)
# --------------------------------------------------------------------------- #
def _tokens(label):
    """Whole arrow tokens of a basis label (a vertex idempotent has none)."""
    if label.startswith("e_"):
        return ()
    return tuple(label.split("*"))


def _f_length(label, new_arrows):
    """The ``F``-length of a basis label = number of new-arrow occurrences (matched
    as WHOLE tokens, so ``al`` is never mistaken for ``a``)."""
    return sum(1 for t in _tokens(label) if t in new_arrows)


def _require_presented(A, what):
    if A.quiver is None or A.relations is None:
        raise QuiverlabError(
            f"{what} needs a quiver presentation (to read the arrow subset F and "
            f"extract I_B = ker pi); this algebra is structure-constant only",
            hint="present A via Quiver(...).algebra(...)")


# --------------------------------------------------------------------------- #
# the Extension object
# --------------------------------------------------------------------------- #
@dataclass
class Extension:
    """``B <= A`` by arrow removal (CLMS Def. 5.2). A **data report** -- read the
    fields / call the relative-path methods; no ``__bool__``."""
    A: object
    B: object
    new_arrows: tuple
    dim_A: int
    dim_B: int
    dim_quotient: int
    # A-basis index partition (F-length 0 spans B's image; F-length >= 1 spans A/B)
    ffree_idx: tuple = _field(default=())
    rel_idx: tuple = _field(default=())          # A-basis indices of the relative paths
    note: str = ""

    # -- the A/B basis ------------------------------------------------------- #
    def relative_paths(self):
        """The ``A/B`` basis: the ``A``-basis labels of positive ``F``-length
        (CLMS Def. 5.9-5.10). A list of labels (strings)."""
        labels = self.A.basis_labels
        return [labels[i] for i in self.rel_idx]

    def _new_arrow_set(self):
        return set(self.new_arrows)

    def length_index(self):
        """CLMS Def. 5.19: ``max F-length over an A-basis + 1``. When ``A/B`` is
        tensor-nilpotent the nilpotency index is ``<=`` this (finite since ``A`` is
        f.d.), so ``(A/B)^{ox L} = 0`` iff ``A/B`` is nilpotent."""
        Fset = self._new_arrow_set()
        return max((_f_length(l, Fset) for l in self.A.basis_labels), default=0) + 1

    # -- relative-path tensor powers over B (CLMS Def. 2.3 / 5.x) ------------- #
    def _tensor_data(self):
        """Cache ``(nR, R_right, R_left)``: the right/left action of every
        ``B``-generator (vertex idempotent + kept arrow) on the relative-path basis,
        expressed in R-local coordinates. Built once, reused by every power."""
        cached = getattr(self, "_td_cache", None)
        if cached is not None:
            return cached
        A = self.A
        dom = A.domain
        labels = A.basis_labels
        Fset = self._new_arrow_set()
        # B-generators: vertex idempotents + kept arrows (F-free single tokens)
        gens = [i for i, l in enumerate(labels) if l.startswith("e_")]
        gens += [i for i, l in enumerate(labels)
                 if _f_length(l, Fset) == 0 and len(_tokens(l)) == 1]
        nR = len(self.rel_idx)

        def projR(vec):
            return [vec[self.rel_idx[k]] for k in range(nR)]

        R_right, R_left = {}, {}
        for k, ai in enumerate(self.rel_idx):
            er = A._basis_vec(ai)
            for g in gens:
                eg = A._basis_vec(g)
                R_right[(k, g)] = projR(A.multiply(er, eg))   # r . g
                R_left[(k, g)] = projR(A.multiply(eg, er))    # g . r
        cached = (nR, tuple(gens), R_right, R_left)
        self._td_cache = cached
        return cached

    def _flat(self, tup, nR):
        idx = 0
        for t in tup:
            idx = idx * nR + t
        return idx

    def _tensor_relations(self, m):
        """The relation rows of ``(A/B)^{ox_k m} / <..(x_i . g) ox x_{i+1}.. -
        ..x_i ox (g . x_{i+1})..>`` (``g`` over ``B``-generators, adjacent slots),
        plus ``ncols = |R|^m``. Loud when ``|R|^m`` exceeds the cell guard."""
        A = self.A
        dom = A.domain
        nR, gens, R_right, R_left = self._tensor_data()
        ncols = nR ** m
        if ncols > _MAX_TENSOR_CELLS:
            raise QuiverlabError(
                f"tensor power (A/B)^(ox {m}) has |R|^{m} = {ncols} columns, past the "
                f"cell guard {_MAX_TENSOR_CELLS}",
                hint="the direct tensor route is infeasible here; use the certificate "
                     "route or a smaller cap")
        rows = []
        for tup in itertools.product(range(nR), repeat=m):
            for i in range(m - 1):
                for g in gens:
                    lvec = R_right[(tup[i], g)]         # x_i . g  (combo over R)
                    rvec = R_left[(tup[i + 1], g)]      # g . x_{i+1}
                    acc = {}
                    for s, c in enumerate(lvec):
                        if not dom.is_zero(c):
                            f = self._flat(tup[:i] + (s,) + tup[i + 1:], nR)
                            acc[f] = dom.add(acc.get(f, dom.zero()), c)
                    for s, c in enumerate(rvec):
                        if not dom.is_zero(c):
                            f = self._flat(tup[:i + 1] + (s,) + tup[i + 2:], nR)
                            acc[f] = dom.add(acc.get(f, dom.zero()), dom.neg(c))
                    if any(not dom.is_zero(v) for v in acc.values()):
                        dense = [dom.zero()] * ncols
                        for f, c in acc.items():
                            dense[f] = c
                        rows.append(dense)
        return rows, ncols

    def _tensor_rref(self, m):
        """Cache the row-reduced relation matrix ``(Rr, pivots, ncols)`` of
        ``(A/B)^{ox_B m}`` -- reused by ``tensor_power_dim`` and every membership
        test (so multiple ``has_J_interrupter`` calls do NOT re-eliminate)."""
        cache = getattr(self, "_rref_cache", None)
        if cache is None:
            cache = {}
            self._rref_cache = cache
        if m not in cache:
            rows, ncols = self._tensor_relations(m)
            Rr, pivots = rref(rows, self.A.domain) if rows else ([], [])
            cache[m] = (Rr, pivots, ncols)
        return cache[m]

    def tensor_power_dim(self, m):
        """``dim_k (A/B)^{ox_B m}`` (exact). ``m = 0 -> dim B`` is not modelled here
        (``B`` is the tensor unit); ``m >= 1`` by the B-tensor relation quotient."""
        if m <= 0:
            raise QuiverlabError("tensor_power_dim needs m >= 1",
                                 hint="(A/B)^(ox 0) = B is the tensor unit, not modelled")
        nR = len(self.rel_idx)
        if m == 1:
            return nR
        _Rr, pivots, ncols = self._tensor_rref(m)
        return ncols - len(pivots)

    def _tensor_feasible(self, m):
        return len(self.rel_idx) ** m <= _MAX_TENSOR_CELLS

    def _tensor_element_is_zero(self, tup):
        """Is the class of the basis ``m``-tuple ``tup`` (R-local indices) zero in
        ``(A/B)^{ox_B m}``? Reduce ``e_tup`` against the cached relation RREF."""
        dom = self.A.domain
        Rr, pivots, ncols = self._tensor_rref(len(tup))
        v = [dom.zero()] * ncols
        v[self._flat(tup, len(self.rel_idx))] = dom.one()
        for row, pc in zip(Rr, pivots):               # RREF: leading 1 at column pc
            f = v[pc]
            if not dom.is_zero(f):
                for j in range(ncols):
                    rj = row[j]
                    if not dom.is_zero(rj):
                        v[j] = dom.add(v[j], dom.neg(dom.mul(f, rj)))
        return all(dom.is_zero(x) for x in v)

    # -- relative cycles + J-interrupters (CLMS Def. 5.11 / 5.13) ------------- #
    def relative_cycles(self, cap=None):
        """The relative-path cycles: ``A``-basis relative paths that close up
        (source vertex == target vertex, CLMS Def. 5.11). ``cap`` is accepted for
        API symmetry (the A-basis is finite, so all cycles are enumerated)."""
        Q = self.A.quiver
        labels = self.A.basis_labels
        out = []
        for ai in self.rel_idx:
            toks = _tokens(labels[ai])
            if Q.word_source(toks) == Q.word_target(toks):
                out.append(labels[ai])
        return out

    def has_J_interrupter(self, cycle_label):
        """Does the relative cycle ``cycle_label`` carry a ``J``-interrupter (CLMS
        Def. 5.13)? The exact, coordinate-free manifestation: the cycle's self-tensor
        ``w ox_B w`` vanishes -- the cyclic join across a new arrow reduces into
        ``B``, so every tensor power collapses there. (``w ox w != 0`` == the cycle
        survives == no ``J``-interrupter, the Ex. 5.5 witness.)"""
        rpos = {ai: k for k, ai in enumerate(self.rel_idx)}
        k = rpos[self.A.basis_labels.index(cycle_label)]
        return self._tensor_element_is_zero((k, k))

    # -- A/B as a B-bimodule ------------------------------------------------- #
    def _b_images(self):
        """``{B-basis index: A-coordinate vector}`` -- the embedding ``B ↪ A`` on
        ``B``'s basis (a product of the kept-arrow images). Cached."""
        cached = getattr(self, "_bimg_cache", None)
        if cached is not None:
            return cached
        A = self.A
        B = self.B
        labels = A.basis_labels
        img = {name: A._basis_vec(labels.index(name))
               for name in A.quiver.arrows if name not in self._new_arrow_set()}
        out = []
        for blabel in B.basis_labels:
            if blabel.startswith("e_"):
                out.append(A._basis_vec(labels.index(blabel)))
            else:
                toks = blabel.split("*")
                av = img[toks[0]]
                for t in toks[1:]:
                    av = A.multiply(av, img[t])
                out.append(av)
        self._bimg_cache = out
        return out

    def quotient_bimodule(self):
        """``A/B`` as a ``B``-bimodule (a :class:`hochschild.coefficients.Bimodule`
        over ``B``): ``dim_M = dim_quotient``; ``Lact[j]`` / ``Ract[j]`` are the
        ``B``-basis element ``b_j`` acting on the relative paths by multiplication in
        ``A`` followed by the projection to ``A/B`` (drop the F-free part). The
        coefficient the Jacobi-Zariski relative complex + the one-sided module read."""
        from quiverlab.hochschild.coefficients import Bimodule
        A = self.A
        dom = A.domain
        B = self.B
        rel = list(self.rel_idx)
        nR = len(rel)
        bimgs = self._b_images()

        def projR(vec):
            return [vec[rel[k]] for k in range(nR)]

        Lact, Ract = [], []
        for bj in bimgs:
            Lj, Rj = [], []
            for k, ai in enumerate(rel):
                er = A._basis_vec(ai)
                Lj.append(projR(A.multiply(bj, er)))     # b_j . r
                Rj.append(projR(A.multiply(er, bj)))     # r . b_j
            Lact.append(Lj)
            Ract.append(Rj)
        return Bimodule(B, nR, Lact, Ract, name="A/B")


# --------------------------------------------------------------------------- #
# enveloping algebra B^e = B (x) B^op as a bound quiver algebra (Task II2)
# --------------------------------------------------------------------------- #
def enveloping_algebra(B):
    """``B^e = B (x) B^op`` as a **bound quiver algebra** (the product quiver
    ``Q_B (x) Q_B^op`` with the relations extracted + ``dim = (dim B)^2`` certified
    by ``present_from_pi`` against the shipped ``TensorProduct(B, B.opposite())``
    structure constants). The first first-class enveloping algebra in quiverlab (the
    Hochschild engines only ever handle ``A^e`` internally). Used ONLY by the
    ``gl.dim B = infinity`` fallback of leg (ii) -- the primary ``gl.dim`` route
    never builds it.

    Because ``present_from_pi`` certifies ``dim B^e = (dim B)^2`` and the generators
    (arrow (x) idempotent, idempotent (x) arrow^op) map onto ``TensorProduct``, the
    map ``kQ_e ->> B (x) B^op`` is a surjection of equal dimension, so ``B^e`` is
    ISO to ``B (x) B^op`` -- the dimension certificate is the algebra iso witness.
    """
    from quiverlab.combinat.quiver import Quiver
    from quiverlab.families.tensor import TensorProduct

    _require_presented(B, "enveloping_algebra")
    dom = B.domain
    Bop = B.opposite()
    T = TensorProduct(B, Bop)
    tindex = {lab: i for i, lab in enumerate(T.basis_labels)}
    verts = [(u, v) for u in B.quiver.vertices for v in Bop.quiver.vertices]
    arrows, img = {}, {}
    for al, (su, tu) in B.quiver.arrows.items():          # al (x) e_v (left factor)
        for v in Bop.quiver.vertices:
            name = f"L_{al}_{v}"
            arrows[name] = ((su, v), (tu, v))
            img[name] = T._basis_vec(tindex[f"{al}(x)e_{v}"])
    for be, (sv, tv) in Bop.quiver.arrows.items():        # e_u (x) be^op (right factor)
        for u in B.quiver.vertices:
            name = f"R_{be}_{u}"
            arrows[name] = ((u, sv), (u, tv))
            img[name] = T._basis_vec(tindex[f"e_{u}(x){be}"])
    Qe = Quiver(verts, arrows)
    maxlen = max((len(_tokens(l)) for l in B.basis_labels), default=1)
    base_bound = 2 * maxlen + 1
    Be = present_from_pi(Qe, img, T, dom, B.dim ** 2, base_bound,
                         citations=_EXT_CITATIONS)
    return Be


# --------------------------------------------------------------------------- #
# the constructor
# --------------------------------------------------------------------------- #
def arrow_removal_subalgebra(A, new_arrows):
    """Build ``B <= A`` by designating ``new_arrows`` (``F``) as new; ``B`` is the
    subalgebra generated by the kept arrows. Returns an :class:`Extension`.

    ``I_B = ker(pi: kQ_B -> A)`` is extracted and ``dim B`` certified by the shipped
    ``present_from_pi`` (the extension axiom ``J cap B = 0`` == ``dim B`` equals the
    F-free A-basis count). Loud ``QuiverlabError`` for a structure-constant ``A`` or
    an unknown arrow name.
    """
    from quiverlab.combinat.quiver import Quiver

    _require_presented(A, "arrow_removal_subalgebra")
    new_arrows = tuple(new_arrows)
    Fset = set(new_arrows)
    for a in new_arrows:
        if a not in A.quiver.arrows:
            raise QuiverlabError(
                f"arrow_removal_subalgebra: {a!r} is not an arrow of Q_A",
                hint=f"arrows are {sorted(A.quiver.arrows)}")

    labels = A.basis_labels
    ffree_idx = tuple(i for i, l in enumerate(labels) if _f_length(l, Fset) == 0)
    rel_idx = tuple(i for i, l in enumerate(labels) if _f_length(l, Fset) >= 1)
    dim_expected = len(ffree_idx)

    # kept arrows -> Q_B; each kept arrow's image is its coordinate in A
    kept = {n: e for n, e in A.quiver.arrows.items() if n not in Fset}
    QB = Quiver(list(A.quiver.vertices), kept)
    img = {name: A._basis_vec(labels.index(name)) for name in kept}
    base_bound = max((len(_tokens(labels[i])) for i in ffree_idx), default=1) + 1
    # present_from_pi certifies dim(kQ_B/ker pi) == dim_expected (widens once, loud else)
    B = present_from_pi(QB, img, A, A.domain, dim_expected, base_bound,
                        citations=_EXT_CITATIONS)

    _certify_decomposition(A, B, img, ffree_idx, rel_idx)

    return Extension(
        A=A, B=B, new_arrows=new_arrows,
        dim_A=A.dim, dim_B=B.dim, dim_quotient=len(rel_idx),
        ffree_idx=ffree_idx, rel_idx=rel_idx)


def _certify_decomposition(A, B, img, ffree_idx, rel_idx):
    """Certify ``A = image(B) (+) span(relative paths)`` as k-spaces: every
    ``B``-basis element embeds into ``A`` with support inside the F-free coordinates
    (so ``A/B`` really is spanned by the relative paths). Loud otherwise -- an
    ``F``-free product whose normal form is F-positive is out of the honest
    relative-path input model (M1)."""
    dom = A.domain
    ffree = set(ffree_idx)
    labels = A.basis_labels
    for blabel in B.basis_labels:
        if blabel.startswith("e_"):
            av = A._basis_vec(labels.index(blabel))
        else:
            toks = blabel.split("*")
            av = img[toks[0]]
            for t in toks[1:]:
                av = A.multiply(av, img[t])
        for j in rel_idx:
            if not dom.is_zero(av[j]):
                raise QuiverlabError(
                    "arrow_removal_subalgebra: the subalgebra B does not sit inside "
                    "span(F-free basis paths) -- an F-free product rewrites to an "
                    "F-positive normal form, so A/B is not spanned by the relative "
                    "paths (out of the honest input model, M1)",
                    hint="re-present A on a quiver that exhibits B's arrows")
