"""The "extension by arrows and relations" input model (CLMS Def. 5.1/5.2) plus the
relative-path combinatorics for the Han bounded-extension recognizer (Plan 73, R7).

Cibils-Lanzilotta-Marcos-Solotar, ``2101.02597`` (J. Algebra 2022). Given a
finite-dimensional ``A = kQ_A/I_A`` and a subset ``F`` of ``(Q_A)_1`` of arrows
designated as **new**, the subalgebra ``B <= A`` generated by the **kept** arrows
``(Q_A)_1 \\ F`` (and the vertices) is an "extension by arrows and relations":
``B = kQ_B/I_B`` with ``Q_B = (Q_0, (Q_A)_1 \\ F)`` and ``I_B = ker(pi: kQ_B -> A)``.
The ``B``-bimodule ``A/B`` is spanned by the **relative paths** -- the ``A``-basis
paths of positive ``F``-length (>= 1 new arrow, CLMS Def. 5.9-5.10).

Composition is left-to-right (quiverlab convention); the CLMS paper composes
right-to-left, so every transcribed path is translated.

**Shared substrate (P72 seam).** P72 (``hochschild/arrow_removal.py``) ships the
inert-arrow reductions ``inert_arrows`` / ``remove_arrows`` / ``add_arrows``.
``remove_arrows`` is the **inert special case** (``I_B = I_A`` verbatim);
``arrow_removal_subalgebra`` here is the general constructor (arbitrary ``F``,
induced ``I_B = ker pi`` -- an ``F``-relation can collapse ``F``-free paths, so the
ideal is NOT "drop the ``F``-relations"). P72 is consumed, not re-implemented: the
cross-consistency test ``remove_arrows == arrow_removal_subalgebra`` on an inert
``F`` is the adjudicated seam gate (``tests/families/test_extension.py``). The
honest constructor drives the shipped ``families/_present.py::present_from_pi``
(Plan 44) to extract ``ker pi`` and certify ``dim B``.
"""
from dataclasses import dataclass, field as _field

from quiverlab.errors import QuiverlabError
from quiverlab.families._present import present_from_pi

_EXT_CITATIONS = ("clms_bounded_extensions", "han_conjecture")


# --------------------------------------------------------------------------- #
# relative-path token combinatorics (guards the 'al' vs 'a' whole-token trap)
# --------------------------------------------------------------------------- #
def _tokens(label):
    """Whole arrow tokens of a basis label (a vertex idempotent has none)."""
    if label.startswith("e_"):
        return ()
    return tuple(label.split("*"))


def _f_length(label, new_arrows):
    """The ``F``-length of a basis label = number of new-arrow occurrences (matched
    as WHOLE tokens, so ``al`` is never mistaken for ``a``)."""
    return sum(1 for t in _tokens(label) if t in new_arrows)


def _require_presented(A, what):
    if A.quiver is None or A.relations is None:
        raise QuiverlabError(
            f"{what} needs a quiver presentation (to read the arrow subset F and "
            f"extract I_B = ker pi); this algebra is structure-constant only",
            hint="present A via Quiver(...).algebra(...)")


# --------------------------------------------------------------------------- #
# the Extension object
# --------------------------------------------------------------------------- #
@dataclass
class Extension:
    """``B <= A`` by arrow removal (CLMS Def. 5.2). A **data report** -- read the
    fields / call the relative-path methods; no ``__bool__``."""
    A: object
    B: object
    new_arrows: tuple
    dim_A: int
    dim_B: int
    dim_quotient: int
    # A-basis index partition (F-length 0 spans B's image; F-length >= 1 spans A/B)
    ffree_idx: tuple = _field(default=())
    rel_idx: tuple = _field(default=())          # A-basis indices of the relative paths
    note: str = ""

    # -- the A/B basis ------------------------------------------------------- #
    def relative_paths(self):
        """The ``A/B`` basis: the ``A``-basis labels of positive ``F``-length
        (CLMS Def. 5.9-5.10). A list of labels (strings)."""
        labels = self.A.basis_labels
        return [labels[i] for i in self.rel_idx]

    def _new_arrow_set(self):
        return set(self.new_arrows)


# --------------------------------------------------------------------------- #
# the constructor
# --------------------------------------------------------------------------- #
def arrow_removal_subalgebra(A, new_arrows):
    """Build ``B <= A`` by designating ``new_arrows`` (``F``) as new; ``B`` is the
    subalgebra generated by the kept arrows. Returns an :class:`Extension`.

    ``I_B = ker(pi: kQ_B -> A)`` is extracted and ``dim B`` certified by the shipped
    ``present_from_pi`` (the extension axiom ``J cap B = 0`` == ``dim B`` equals the
    F-free A-basis count). Loud ``QuiverlabError`` for a structure-constant ``A`` or
    an unknown arrow name.
    """
    from quiverlab.combinat.quiver import Quiver

    _require_presented(A, "arrow_removal_subalgebra")
    new_arrows = tuple(new_arrows)
    Fset = set(new_arrows)
    for a in new_arrows:
        if a not in A.quiver.arrows:
            raise QuiverlabError(
                f"arrow_removal_subalgebra: {a!r} is not an arrow of Q_A",
                hint=f"arrows are {sorted(A.quiver.arrows)}")

    labels = A.basis_labels
    ffree_idx = tuple(i for i, l in enumerate(labels) if _f_length(l, Fset) == 0)
    rel_idx = tuple(i for i, l in enumerate(labels) if _f_length(l, Fset) >= 1)
    dim_expected = len(ffree_idx)

    # kept arrows -> Q_B; each kept arrow's image is its coordinate in A
    kept = {n: e for n, e in A.quiver.arrows.items() if n not in Fset}
    QB = Quiver(list(A.quiver.vertices), kept)
    img = {name: A._basis_vec(labels.index(name)) for name in kept}
    base_bound = max((len(_tokens(labels[i])) for i in ffree_idx), default=1) + 1
    # present_from_pi certifies dim(kQ_B/ker pi) == dim_expected (widens once, loud else)
    B = present_from_pi(QB, img, A, A.domain, dim_expected, base_bound,
                        citations=_EXT_CITATIONS)

    _certify_decomposition(A, B, img, ffree_idx, rel_idx)

    return Extension(
        A=A, B=B, new_arrows=new_arrows,
        dim_A=A.dim, dim_B=B.dim, dim_quotient=len(rel_idx),
        ffree_idx=ffree_idx, rel_idx=rel_idx)


def _certify_decomposition(A, B, img, ffree_idx, rel_idx):
    """Certify ``A = image(B) (+) span(relative paths)`` as k-spaces: every
    ``B``-basis element embeds into ``A`` with support inside the F-free coordinates
    (so ``A/B`` really is spanned by the relative paths). Loud otherwise -- an
    ``F``-free product whose normal form is F-positive is out of the honest
    relative-path input model (M1)."""
    dom = A.domain
    ffree = set(ffree_idx)
    labels = A.basis_labels
    for blabel in B.basis_labels:
        if blabel.startswith("e_"):
            av = A._basis_vec(labels.index(blabel))
        else:
            toks = blabel.split("*")
            av = img[toks[0]]
            for t in toks[1:]:
                av = A.multiply(av, img[t])
        for j in rel_idx:
            if not dom.is_zero(av[j]):
                raise QuiverlabError(
                    "arrow_removal_subalgebra: the subalgebra B does not sit inside "
                    "span(F-free basis paths) -- an F-free product rewrites to an "
                    "F-positive normal form, so A/B is not spanned by the relative "
                    "paths (out of the honest input model, M1)",
                    hint="re-present A on a quiver that exhibits B's arrows")
