"""TruncatedPathAlgebra kQ/rad^r (spec §3.4). rad^r is generated by every path of
length r, so the monomial ideal is exactly the set of length-r arrow-words; the
monomial builder's suffix automaton then also kills all longer words. r >= 2."""
from quiverlab.combinat.quiver import Quiver
from quiverlab.errors import QuiverlabError
from quiverlab.families.dynkin import dynkin_quiver


def _length_r_paths(quiver, r):
    words = [(a,) for a in quiver.arrows]
    for _ in range(r - 1):
        nxt = []
        for w in words:
            for a in quiver.arrows:
                if quiver.target(w[-1]) == quiver.source(a):
                    nxt.append(w + (a,))
        words = nxt
    return words


def TruncatedPathAlgebra(type_or_quiver, r, orientation="linear", field=None):
    if not (isinstance(r, int) and not isinstance(r, bool) and r >= 2):
        raise QuiverlabError(f"TruncatedPathAlgebra r={r!r}: need integer r >= 2",
                             hint="r = 1 kills the arrows; use r >= 2")
    Q = type_or_quiver if isinstance(type_or_quiver, Quiver) else \
        dynkin_quiver(type_or_quiver, orientation)
    rels = ["*".join(w) for w in _length_r_paths(Q, r)]
    A = Q.algebra(relations=rels, field=field)
    A._family_citations = ("path_algebra", "bardzell")
    return A
