"""Validation battery (c): CS resolution HH pinned against REAL literature / bank
oracles (spec-§6 "Examples"; Plan-04 Task 10).

Unlike batteries (a) [CS == Bardzell] and (b) [CS == bar], which compare two of the
library's OWN engines, this battery pins cs_(co)homology_dims against VALUES THAT
EXIST OUTSIDE THE LIBRARY -- classical Hochschild computations and one bank-derived
vector -- so a regression that corrupted BOTH CS and bar identically would still be
caught. Every pinned number carries its provenance inline (published result / bank /
bar cross-check per the brief's rule "where no published vector is at hand, cross-check
bar and cite 'bar cross-check'").

===========================================================================
TRANSCRIPTION DEVIATION FROM p04-task-10-brief.md  (flagged per the brief's
minimal-fix clause: "if transcribed code fails its own transcribed tests, apply
the MINIMAL fix and flag prominently"):

  *** The brief's k[x]/x^n char-0 oracle is MATHEMATICALLY WRONG for n >= 3. ***

  The brief transcribes  `assert d[0] == n and all(v == 1 for v in d[1:])`
  with the inline claim "HH_i = 1 (i>=1) char 0 (p | n)".  That is FALSE for
  n >= 3.  The classical value is

        dim_k HH_0(k[x]/x^n) = n ,   dim_k HH_i(k[x]/x^n) = n - 1  (i >= 1),

  for char k = 0 (indeed whenever n is invertible, p does not divide n).  Derivation:
  A = k[x]/(x^n) has the period-2 minimal bimodule resolution with alternating
  differentials u = x@1 - 1@x  and  v = sum_{i+j=n-1} x^i @ x^j.  Applying
  A @_{A^e} - collapses u to multiplication by (x - x) = 0 and v to multiplication
  by sum_{i+j=n-1} x^i x^j = n x^{n-1}.  With n invertible the homology of
  ... -> A --0--> A --*n x^{n-1}--> A --0--> A  is
        HH_0 = A                 (dim n),
        HH_1 = A / (x^{n-1})     (dim n-1),
        HH_2 = ann(x^{n-1}) = (x)(dim n-1),  and periodically n-1 thereafter.
  (See e.g. Loday, "Cyclic Homology", and the truncated-polynomial computations in
  BACH.)  The brief's "1" is correct ONLY at n = 2, where n - 1 = 1 by coincidence.

  Confirmed empirically at pin time on THIS branch: both the CS engine
  (cs_homology_dims) and the disjoint bar oracle (hochschild_homology_dims) return
  [n, n-1, n-1, ...] for every n in {2,3,4,5} at every feasible depth; the verbatim
  brief assertion FAILS the CS engine at n = 3 (got [3,2,2,2,2,2,2]).  The oracle is
  CORRECTED to the true value n-1; it is NOT loosened, NOT faked, and the correction
  is a published result, not an invented one.

  The char-5 pathology row [5,5,5,5,5,5,5] (p | n: v collapses to 5 x^4 = 0, so both
  differentials vanish and every HH_i = A, dim 5) is transcribed VERBATIM -- it is
  correct as written and confirmed by CS and bar.
===========================================================================
"""
import pytest
from quiverlab import Quiver, CC, GF
from quiverlab.resolutions_cs.homology import cs_cohomology_dims, cs_homology_dims
from quiverlab.hochschild.bar import hochschild_cohomology_dims
pytest.importorskip("quiverlab.groebner")


def _build_gentle():
    """A small GENTLE algebra: the 2-cycle 1 ->a 2 ->b 1 with rad^2 = 0, i.e.
    kQ/(ab, ba).  Gentle in the sense of Assem-Skowronski (Algebra i Analiz, 1987):
    <=2 arrows in/out per vertex, I generated by length-2 paths, and each arrow lies
    in exactly one zero and no nonzero length-2 relation.  It is self-injective
    (dim = 4: e1, e2, a, b), so its Hochschild cohomology is nonzero in every degree
    -- HH^*(top 3) = [1,1,1,1] -- which makes the CS<->bar agreement below a
    discriminating check rather than a run of zeros.  ORACLE: bar cross-check (no
    single published dim vector is pinned; the assertion compares CS to the disjoint
    normalized-bar engine on the same algebra)."""
    return Quiver([1, 2], {"a": (1, 2), "b": (2, 1)}).algebra(
        relations=["a*b", "b*a"], field=CC)


def test_kxn_across_characteristics():
    # ORACLE: k[x]/x^n, classical.  char 0 (p | n): HH_0 = n, HH_i = n-1 (i>=1).
    # See the module-level TRANSCRIPTION DEVIATION note -- the brief's "1" is wrong
    # for n >= 3; n-1 is the published value, cross-confirmed here by the bar oracle.
    for n in (2, 3, 4, 5):
        A = Quiver([1], {"x": (1, 1)}).algebra(relations=[f"x^{n}"], field=CC)
        d = cs_homology_dims(A, 6).dims
        assert d[0] == n and all(v == n - 1 for v in d[1:])
    # char 5 pathology (p | n): v = n x^{n-1} = 5 x^4 = 0, so every HH_i = A, dim 5.
    A5 = Quiver([1], {"x": (1, 1)}).algebra(relations=["x^5"], field=GF(5))
    assert cs_homology_dims(A5, 6).dims == [5, 5, 5, 5, 5, 5, 5]     # p | n pathology


def test_bgms_quantum_ci_homology():
    # ORACLE: BGMS quantum complete intersection k<x,y>/(x^2, y^2, yx - xi*xy), xi=2
    # (a non-root-of-unity q, char 0).  This is the CS paper's own recovered example
    # (spec-§Examples cites [BGMS] Buchweitz-Green-Madsen-Solberg, Math. Res. Lett.
    # 12 (2005), and [BE] Bergh-Erdmann).  Pinned dim vector HH_• = [3,2,2,...] is
    # BANK-DERIVED and cross-confirmed here by the bar oracle at pin time.
    A = Quiver([1], {"x": (1, 1), "y": (1, 1)}).algebra(
        relations=["x*x", "y*y", "y*x - 2*x*y"], field=CC)
    assert cs_homology_dims(A, 8).dims == [3, 2, 2, 2, 2, 2, 2, 2, 2]


def test_hereditary_dynkin_happel():
    # ORACLE: Happel's theorem -- A hereditary ==> HH^i(A) = 0 for i >= 2 (Happel,
    # "Hochschild cohomology of finite-dimensional algebras", SLN 1404, 1989).
    # Linear A_3 = k(1->2->3), no relations: HH^0 = center = k (dim 1), and being a
    # tree quiver HH^1 = 0 as well, so HH^* = [1,0,0,0,0].
    A = Quiver([1, 2, 3], {"a": (1, 2), "b": (2, 3)}).algebra(relations=[], field=CC)
    d = cs_cohomology_dims(A, 4).dims
    assert d[0] == 1 and d[2:] == [0, 0, 0]


def test_gentle_case_matches_bar():
    # ORACLE: bar cross-check (see _build_gentle docstring for the source of the
    # algebra).  CS cohomology must agree degreewise with the disjoint bar engine.
    A = _build_gentle()
    assert cs_cohomology_dims(A, 3).dims == hochschild_cohomology_dims(A, 3).dims
