"""Algebra-class recognizers: is_semisimple .. is_gentle (Plan 38 / C2).

Each takes an Algebra A and returns a bool. Recognizers that need the quiver
presentation (everything except the two Loewy-length ones) refuse loudly on a
structure-constant algebra, mirroring modules.builders._require_provenance.

The special-biserial / string / gentle family turns on ideal membership of
length-2 paths, decided EXACTLY through the Groebner reduction system
(resolutions_cs.build.reduction_system_of): a length-2 path a*b lies in I iff
its normal form is zero. References: Assem-Simson-Skowronski (ASS 2006),
Butler-Ringel (string modules), Assem-Skowronski (gentle algebras)."""
from quiverlab.errors import QuiverlabError


def _require_quiver(A, what):
    if A.quiver is None or A.relations is None:
        raise QuiverlabError(
            f"{what} needs the quiver presentation",
            hint="build the algebra via Quiver.algebra(...); structure-constant "
                 "algebras carry no quiver")


# -- Loewy-length recognizers (any presentation) ------------------------------
def is_semisimple(A) -> bool:
    """True iff A is semisimple: Loewy length 1 (rad A = 0)."""
    return A.loewy_length() == 1


def is_radical_square_zero(A) -> bool:
    """True iff rad^2 A = 0: Loewy length <= 2."""
    return A.loewy_length() <= 2


# -- structural recognizers (need the quiver) ---------------------------------
def is_hereditary(A) -> bool:
    """True iff A is hereditary (gl.dim <= 1): a path algebra kQ with Q acyclic
    and no relations. An admissible ideal I != 0 forces gl.dim >= 2, so any
    relation makes A non-hereditary."""
    _require_quiver(A, "is_hereditary")
    return (not A.relations) and A.quiver.is_acyclic()


def is_basic(A) -> bool:
    """True for every kQ/I presentation: the vertex idempotents e_v are a
    complete set of primitive orthogonal idempotents whose indecomposable
    projectives e_v A are pairwise non-isomorphic, so A is basic."""
    _require_quiver(A, "is_basic")
    return True


def _in_degree(Q):
    d = {v: 0 for v in Q.vertices}
    for (_s, t) in Q.arrows.values():
        d[t] += 1
    return d


def _out_degree(Q):
    d = {v: 0 for v in Q.vertices}
    for (s, _t) in Q.arrows.values():
        d[s] += 1
    return d


def is_nakayama(A) -> bool:
    """True iff the underlying quiver is a disjoint union of linear A_n paths and
    single oriented cycles: every vertex has in-degree <= 1 and out-degree <= 1
    (each connected component is then uniserial)."""
    _require_quiver(A, "is_nakayama")
    Q = A.quiver
    ind, outd = _in_degree(Q), _out_degree(Q)
    return all(ind[v] <= 1 and outd[v] <= 1 for v in Q.vertices)


def _len2_in_ideal(rs, a, b) -> bool:
    """True iff the length-2 path a*b (first a then b) lies in I: its normal form
    under the reduction system is zero. Assumes a*b is composable
    (target(a) = source(b)) -- the callers only pass composable pairs."""
    nf = rs.normal_form((a, b))
    return all(rs.domain.is_zero(c) for c in nf.values())


def _is_monomial_ideal(A) -> bool:
    return all(r.is_monomial for r in A.relations)


def is_special_biserial(A) -> bool:
    """Special biserial (ASS): (1) every vertex has <= 2 arrows in and <= 2 out;
    (2) for every arrow b, at most one arrow c with b*c not in I and at most one
    arrow a with a*b not in I."""
    _require_quiver(A, "is_special_biserial")
    Q = A.quiver
    ind, outd = _in_degree(Q), _out_degree(Q)
    if any(ind[v] > 2 or outd[v] > 2 for v in Q.vertices):
        return False
    from quiverlab.resolutions_cs.build import reduction_system_of
    rs = reduction_system_of(A)
    arrows = list(Q.arrows.items())                 # (name, (source, target))
    for b, (bs, bt) in arrows:
        after = [c for c, (cs, _ct) in arrows
                 if cs == bt and not _len2_in_ideal(rs, b, c)]
        if len(after) > 1:
            return False
        before = [a for a, (_asrc, at) in arrows
                  if at == bs and not _len2_in_ideal(rs, a, b)]
        if len(before) > 1:
            return False
    return True


def is_string(A) -> bool:
    """String algebra: special biserial with a MONOMIAL ideal I."""
    _require_quiver(A, "is_string")
    return is_special_biserial(A) and _is_monomial_ideal(A)


def is_gentle(A) -> bool:
    """Gentle algebra: a string algebra whose ideal is generated by length-2
    paths, plus the dual biserial condition -- for every arrow b, at most one
    arrow c with b*c IN I and at most one arrow a with a*b IN I."""
    _require_quiver(A, "is_gentle")
    if not is_string(A):
        return False
    if not all(r.is_monomial and r.max_length == 2 for r in A.relations):
        return False
    Q = A.quiver
    from quiverlab.resolutions_cs.build import reduction_system_of
    rs = reduction_system_of(A)
    arrows = list(Q.arrows.items())
    for b, (bs, bt) in arrows:
        after_in = [c for c, (cs, _ct) in arrows
                    if cs == bt and _len2_in_ideal(rs, b, c)]
        if len(after_in) > 1:
            return False
        before_in = [a for a, (_asrc, at) in arrows
                     if at == bs and _len2_in_ideal(rs, a, b)]
        if len(before_in) > 1:
            return False
    return True
