"""AG (Avella-Alaminos-Geiss 2008) derived invariant for gentle algebras.

Self-cert (convention-INDEPENDENT): permitted & forbidden threads each PARTITION the
arrows; sum of the pair n-components = 2|Q_0| - |Q_1| (the number of permitted
threads d_A) and sum of m-components = |Q_1| (every arrow in one forbidden thread).
Literature: AAG 2008 / Nakaoka (arXiv:1811.00775) worked values, reproduced verbatim.
Cross-engine: derived-invariance -- a gentle algebra and its opposite share the
invariant up to the (n,m)<->(m,n) order.

PLAN CORRECTIONS (documented): (1) the plan's guessed pin AG(kA3/(ab)) = {(2,2)} was
based on counting permitted ARROWS for n; the AAG algorithm (verified against
Nakaoka's Example 2.15, {(3,2),(2,2),(0,3)}) counts permitted THREADS for n, giving
{(4,2)}. (2) the plan's self-cert "sum n = sum m = |Q_1|" is corrected to
sum n = 2|Q_0|-|Q_1|, sum m = |Q_1| (the actual AAG identity)."""
import pytest

from quiverlab import Quiver
from quiverlab.errors import QuiverlabError
from quiverlab.fields import QQ
from quiverlab.strings.ag import (ag_invariant, forbidden_threads,
                                  permitted_threads)

selfcert = pytest.mark.oracle_selfcert
lit = pytest.mark.oracle_literature
xeng = pytest.mark.oracle_crossengine


def _gentle_a3():
    return Quiver([1, 2, 3], {"a": (1, 2), "b": (2, 3)}).algebra(
        relations=["a*b"], field=QQ)


def _two_cycle():
    return Quiver([1, 2], {"a": (1, 2), "b": (2, 1)}).algebra(
        relations=["a*b", "b*a"], field=QQ)


def _paper_example_2_15():
    # Nakaoka arXiv:1811.00775 Example 2.15: I = {be*ga, ga*lm, lm*be, ze*ka}.
    return Quiver(["a", "b", "c", "d", "f", "g"], {
        "al": ("a", "c"), "be": ("c", "b"), "ga": ("b", "d"), "lm": ("d", "c"),
        "ze": ("b", "f"), "th": ("d", "f"), "ka": ("f", "g")}).algebra(
        ["be*ga", "ga*lm", "lm*be", "ze*ka"], QQ)


def _arrows_covered(threads):
    seen = []
    for t in threads:
        seen += list(t)
    return sorted(seen)


@selfcert
@pytest.mark.parametrize("factory", [_gentle_a3, _two_cycle, _paper_example_2_15])
def test_threads_partition_the_arrows(factory):
    A = factory()
    arrows = sorted(A.quiver.arrows)
    assert _arrows_covered(permitted_threads(A)) == arrows
    assert _arrows_covered(forbidden_threads(A)) == arrows


@selfcert
@pytest.mark.parametrize("factory", [_gentle_a3, _two_cycle, _paper_example_2_15])
def test_invariant_sums(factory):
    A = factory()
    inv = ag_invariant(A)
    nv, na = len(A.quiver.vertices), len(A.quiver.arrows)
    assert sum(n for n, _ in inv.pairs) == 2 * nv - na     # = d_A, # permitted threads
    assert sum(m for _, m in inv.pairs) == na              # = |Q_1|, forbidden arrows


@lit
def test_ag_of_gentle_a3():
    # AAG (Nakaoka blossoming): one orbit of the 4 permitted threads, one antipath of
    # length 2 -> {(4,2)}. (Plan's {(2,2)} counted arrows for n; corrected.)
    assert ag_invariant(_gentle_a3()).as_multiset() == {(4, 2): 1}


@lit
def test_ag_of_two_cycle():
    # two permitted singletons in one orbit (2,0); one cyclic forbidden thread (0,2).
    assert ag_invariant(_two_cycle()).as_multiset() == {(2, 0): 1, (0, 2): 1}


@lit
def test_ag_of_paper_example_2_15():
    # Nakaoka arXiv:1811.00775 Example 2.15, tabulated phi_A = {(3,2),(2,2),(0,3)}.
    assert ag_invariant(_paper_example_2_15()).as_multiset() == {
        (3, 2): 1, (2, 2): 1, (0, 3): 1}


@xeng
def test_derived_invariance_under_opposite():
    A = _gentle_a3()
    Aop = A.opposite()
    if Aop.quiver is None or Aop.relations is None:
        pytest.skip("opposite is presentation-less; AG cross-check needs a quiver")
    ms = ag_invariant(A).as_multiset()
    msop = ag_invariant(Aop).as_multiset()
    flipped = {(m, n): c for (n, m), c in msop.items()}
    assert ms == msop or ms == flipped


@selfcert
def test_non_gentle_refused():
    # ideal generated by a length-3 path only (a*b, b*c both nonzero): string but
    # NOT gentle (gentle needs length-2 generators). ["a*b","a*b*c"] would be gentle
    # since a*b*c is redundant given a*b -- use a genuine length-3-only relation.
    A = Quiver([1, 2, 3, 4], {"a": (1, 2), "b": (2, 3), "c": (3, 4)}).algebra(
        relations=["a*b*c"], field=QQ)
    with pytest.raises(QuiverlabError):
        ag_invariant(A)
